import assert from 'node:assert/strict'
import test from 'node:test'

const loadModule = async () => {
  try {
    return await import('./script.js')
  } catch {
    return null
  }
}

const homepageHtml = `
  <!doctype html>
  <html lang="en-US">
    <head>
      <title>Home - Sigvitas</title>
    </head>
    <body>
      <nav>
        <a href="https://sigvitas.com/">Home</a>
        <a href="https://sigvitas.com/about-us/">About Us</a>
        <a href="https://sigvitas.com/get-in-touch/">Get In Touch</a>
      </nav>
      <main>
        <h1>Elevate Your Business To New Heights With Sigvitas</h1>
        <h2>Unlock Your Business's Full Potential with Sigvitas</h2>
        <p>Serving Extraordinary Capabilities with Six Sigma Compliant Solutions</p>
        <p>Leading global provider of consulting and technology solutions</p>
        <p>contact@sigvitas.com</p>
        <p>&copy; 2026 Sigvitas. All Rights Reserved</p>
      </main>
    </body>
  </html>
`

const contactHtml = `
  <!doctype html>
  <html lang="en-US">
    <head>
      <title>Get In Touch - Sigvitas</title>
      <link rel="canonical" href="https://sigvitas.com/get-in-touch/" />
    </head>
    <body>
      <main>
        <h1>Contact Us</h1>
        <p>Transform your ideas into reality with Sigvitas</p>
        <p>Leading global provider of consulting and technology solutions</p>
        <p>contact@sigvitas.com</p>
        <p>235, 1st Floor, L3S Arcade, BEML Layout, 2nd Stage, Rajarajeshwari Nagar, Ring Road, Mysore, Karnataka - 570026, India</p>
      </main>
    </body>
  </html>
`

const sitemapIndexXml = `
  <?xml version="1.0" encoding="UTF-8"?>
  <?xml-stylesheet type="text/xsl" href="//sigvitas.com/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
  <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap><loc>https://sigvitas.com/post-sitemap.xml</loc></sitemap>
    <sitemap><loc>https://sigvitas.com/page-sitemap.xml</loc></sitemap>
    <sitemap><loc>https://sigvitas.com/portfolio-item-sitemap.xml</loc></sitemap>
    <sitemap><loc>https://sigvitas.com/category-sitemap.xml</loc></sitemap>
  </sitemapindex>
  <!-- XML Sitemap generated by Yoast SEO -->
`

const pageSitemapXml = `
  <?xml version="1.0" encoding="UTF-8"?>
  <?xml-stylesheet type="text/xsl" href="//sigvitas.com/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url><loc>https://sigvitas.com/</loc></url>
    <url><loc>https://sigvitas.com/about-us/</loc></url>
    <url><loc>https://sigvitas.com/custom-software-engineering/</loc></url>
    <url><loc>https://sigvitas.com/data-analytics/</loc></url>
    <url><loc>https://sigvitas.com/our-capabilities/</loc></url>
    <url><loc>https://sigvitas.com/get-in-touch/</loc></url>
  </urlset>
  <!-- XML Sitemap generated by Yoast SEO -->
`

const pagesApiJson = JSON.stringify([
  {
    slug: 'about-us',
    status: 'publish',
    link: 'https://sigvitas.com/about-us/',
    title: { rendered: 'About Us' },
  },
  {
    slug: 'data-analytics',
    status: 'publish',
    link: 'https://sigvitas.com/data-analytics/',
    title: { rendered: 'Data Analytics' },
  },
  {
    slug: 'our-capabilities',
    status: 'publish',
    link: 'https://sigvitas.com/our-capabilities/',
    title: { rendered: 'Our Capabilities' },
  },
  {
    slug: 'get-in-touch',
    status: 'publish',
    link: 'https://sigvitas.com/get-in-touch/',
    title: { rendered: 'Get In Touch' },
  },
  {
    slug: 'home',
    status: 'publish',
    link: 'https://sigvitas.com/',
    title: { rendered: 'Home' },
  },
])

const missingCareerRoutePage = {
  status: 404,
  url: 'https://sigvitas.com/careers/',
  html: `
    <!doctype html>
    <html lang="en-US">
      <head>
        <title>Page not found - Sigvitas</title>
        <meta name="robots" content="noindex, follow" />
      </head>
      <body class="error404">
        <h1>Page not found</h1>
        <p>Sigvitas - for all <a href="https://sigvitas.com/our-capabilities/">of your business</a> endeavors</p>
        <a href="mailto:contact@sigvitas.com">contact@sigvitas.com</a>
      </body>
    </html>
  `,
}

test('Sigvitas sentinel pins the verified first-party no-public-jobs surface', async () => {
  const sigvitas = await loadModule()
  assert.ok(sigvitas, 'Expected scraper module at ./script.js')

  assert.equal(sigvitas.SOURCE, 'sigvitas')
  assert.equal(sigvitas.COMPANY, 'Sigvitas')
  assert.equal(sigvitas.HOMEPAGE_URL, 'https://sigvitas.com/')
  assert.equal(sigvitas.CONTACT_URL, 'https://sigvitas.com/get-in-touch/')
  assert.equal(sigvitas.SITEMAP_INDEX_URL, 'https://sigvitas.com/sitemap.xml')
  assert.equal(sigvitas.PAGE_SITEMAP_URL, 'https://sigvitas.com/page-sitemap.xml')
  assert.equal(
    sigvitas.PAGES_API_URL,
    'https://sigvitas.com/wp-json/wp/v2/pages?per_page=100&_fields=slug,link,title,status',
  )
  assert.deepEqual(sigvitas.NO_PUBLIC_CAREERS_ROUTE_URLS, [
    'https://sigvitas.com/careers/',
    'https://sigvitas.com/careers',
    'https://sigvitas.com/career/',
    'https://sigvitas.com/career',
    'https://sigvitas.com/jobs/',
    'https://sigvitas.com/jobs',
    'https://sigvitas.com/join-us/',
    'https://sigvitas.com/join-us',
  ])
  assert.equal(sigvitas.hasOfficialHomepageSignal(homepageHtml), true)
  assert.equal(sigvitas.hasOfficialContactSignal(contactHtml), true)
  assert.equal(sigvitas.hasOfficialSitemapIndexSignal(sitemapIndexXml), true)
  assert.equal(sigvitas.hasOfficialPageSitemapSignal(pageSitemapXml), true)
  assert.equal(sigvitas.hasOfficialPagesApiSignal(pagesApiJson), true)
  assert.equal(sigvitas.hasPublicJobsSignal(homepageHtml), false)
  assert.equal(sigvitas.hasPublicJobsSignal(contactHtml), false)
  assert.equal(sigvitas.hasFirstPartyCareerLikeLink(homepageHtml), false)
  assert.equal(sigvitas.hasFirstPartyCareerLikeLink(contactHtml), false)
  assert.equal(sigvitas.isVerifiedMissingCareerRoute(missingCareerRoutePage), true)
})

test('Sigvitas sentinel returns no jobs only while the verified first-party surfaces stay unchanged', async () => {
  const sigvitas = await loadModule()
  assert.ok(sigvitas, 'Expected scraper module at ./script.js')

  const requestedUrls = []
  const jobs = await sigvitas.createSigvitasScraper().run({
    fetchPage: async (url) => {
      requestedUrls.push(url)

      if (url === sigvitas.HOMEPAGE_URL) return { status: 200, url, html: homepageHtml }
      if (url === sigvitas.CONTACT_URL) return { status: 200, url, html: contactHtml }
      if (url === sigvitas.SITEMAP_INDEX_URL) return { status: 200, url, html: sitemapIndexXml }
      if (url === sigvitas.PAGE_SITEMAP_URL) return { status: 200, url, html: pageSitemapXml }
      if (url === sigvitas.PAGES_API_URL) return { status: 200, url, html: pagesApiJson }
      if (sigvitas.NO_PUBLIC_CAREERS_ROUTE_URLS.includes(url)) return { ...missingCareerRoutePage, url }

      throw new Error(`Unexpected Sigvitas URL: ${url}`)
    },
  })

  assert.deepEqual(requestedUrls, [
    sigvitas.HOMEPAGE_URL,
    sigvitas.CONTACT_URL,
    sigvitas.SITEMAP_INDEX_URL,
    sigvitas.PAGE_SITEMAP_URL,
    sigvitas.PAGES_API_URL,
    ...sigvitas.NO_PUBLIC_CAREERS_ROUTE_URLS,
  ])
  assert.deepEqual(jobs, [])
})

test('Sigvitas exposes runner metadata for a verified no-public-careers provider', async () => {
  const sigvitas = await loadModule()
  assert.ok(sigvitas, 'Expected scraper module at ./script.js')

  assert.deepEqual(sigvitas.getRunnerMetadata(), {
    name: 'sigvitas',
    dryRunFile: 'jobs.json',
    provider: {
      source: 'sigvitas',
      companyName: 'Sigvitas',
      companyCareerPage: 'https://sigvitas.com/',
      alternateCareerPages: [
        'https://sigvitas.com/careers/',
        'https://sigvitas.com/careers',
        'https://sigvitas.com/career/',
        'https://sigvitas.com/career',
        'https://sigvitas.com/jobs/',
        'https://sigvitas.com/jobs',
        'https://sigvitas.com/join-us/',
        'https://sigvitas.com/join-us',
      ],
      officialSurfaceUrls: [
        'https://sigvitas.com/',
        'https://sigvitas.com/get-in-touch/',
        'https://sigvitas.com/sitemap.xml',
        'https://sigvitas.com/page-sitemap.xml',
        'https://sigvitas.com/wp-json/wp/v2/pages?per_page=100&_fields=slug,link,title,status',
      ],
      adapter: 'script',
      atsPlatform: 'official-company-site-no-public-careers',
      countryFilter: 'India',
      parser: 'custom-script',
      paginationStrategy: 'verified-homepage-contact-sitemap-and-wordpress-page-index-validation',
      extractionStrategy: 'verified-first-party-marketing-surface-plus-missing-careers-routes-return-empty',
      normalizationProfile: 'engineering-default',
      companyDomain: 'sigvitas.com',
    },
  })
})

test('Sigvitas sentinel fails closed when the verified no-public-careers contract drifts', async () => {
  const sigvitas = await loadModule()
  assert.ok(sigvitas, 'Expected scraper module at ./script.js')

  await assert.rejects(
    sigvitas.createSigvitasScraper().run({
      fetchPage: async (url) => {
        if (url === sigvitas.HOMEPAGE_URL) {
          return {
            status: 200,
            url,
            html: '<html><body><h1>Unexpected homepage</h1></body></html>',
          }
        }

        throw new Error(`Unexpected Sigvitas URL: ${url}`)
      },
    }),
    /homepage/i,
  )

  await assert.rejects(
    sigvitas.createSigvitasScraper().run({
      fetchPage: async (url) => {
        if (url === sigvitas.HOMEPAGE_URL) return { status: 200, url, html: homepageHtml }
        if (url === sigvitas.CONTACT_URL) return { status: 200, url, html: contactHtml }
        if (url === sigvitas.SITEMAP_INDEX_URL) return { status: 200, url, html: sitemapIndexXml }
        if (url === sigvitas.PAGE_SITEMAP_URL) return { status: 200, url, html: pageSitemapXml }
        if (url === sigvitas.PAGES_API_URL) {
          return {
            status: 200,
            url,
            html: JSON.stringify([
              { slug: 'home', status: 'publish', link: sigvitas.HOMEPAGE_URL, title: { rendered: 'Home' } },
              {
                slug: 'careers',
                status: 'publish',
                link: 'https://sigvitas.com/careers/',
                title: { rendered: 'Careers' },
              },
            ]),
          }
        }

        throw new Error(`Unexpected Sigvitas URL: ${url}`)
      },
    }),
    /pages api/i,
  )

  await assert.rejects(
    sigvitas.createSigvitasScraper().run({
      fetchPage: async (url) => {
        if (url === sigvitas.HOMEPAGE_URL) return { status: 200, url, html: homepageHtml }
        if (url === sigvitas.CONTACT_URL) return { status: 200, url, html: contactHtml }
        if (url === sigvitas.SITEMAP_INDEX_URL) return { status: 200, url, html: sitemapIndexXml }
        if (url === sigvitas.PAGE_SITEMAP_URL) return { status: 200, url, html: pageSitemapXml }
        if (url === sigvitas.PAGES_API_URL) return { status: 200, url, html: pagesApiJson }
        if (url === sigvitas.NO_PUBLIC_CAREERS_ROUTE_URLS[0]) {
          return {
            status: 200,
            url,
            html: '<html><body><h1>Current Openings</h1><a href="/careers/software-engineer">Apply now</a></body></html>',
          }
        }
        if (sigvitas.NO_PUBLIC_CAREERS_ROUTE_URLS.slice(1).includes(url)) return { ...missingCareerRoutePage, url }

        throw new Error(`Unexpected Sigvitas URL: ${url}`)
      },
    }),
    /no-public-careers route changed/i,
  )
})
