/**
 * @file Canonical city name map — single source of truth for all city normalisation.
 * @module scraper/utils/cities
 */

// Key: lowercase raw variant → Value: canonical display name stored in DB.
// To add a new city: add entries here AND mirror the value in Jobify-frontend/src/data/cities.js (same PR).
export const CANONICAL_CITIES = {
  'airoli':         'Airoli',
  // Bangalore / Bengaluru
  'bengaluru':      'Bangalore',
  'bangalore':      'Bangalore',
  'bangalore area': 'Bangalore',
  'blr sez':        'Bangalore',
  // Gurugram / Gurgaon
  'gurugram':       'Gurgaon',
  'gurgaon':        'Gurgaon',
  'jhajjar':        'Jhajjar',
  // Standard names
  'mumbai':         'Mumbai',
  'bombay':         'Mumbai',
  'delhi':          'Delhi',
  'new delhi':      'Delhi',
  'hyderabad':      'Hyderabad',
  'pune':           'Pune',
  'chennai':        'Chennai',
  'madras':         'Chennai',
  'kolkata':        'Kolkata',
  'calcutta':       'Kolkata',
  'kochi':          'Kochi',
  'cochin':         'Kochi',
  'ahmedabad':      'Ahmedabad',
  'hazira':         'Hazira',
  'noida':          'Noida',
  'greater noida':  'Greater Noida',
  'faridabad':      'Faridabad',
  'jaipur':         'Jaipur',
  'coimbatore':     'Coimbatore',
  'bhubaneswar':    'Bhubaneswar',
  'salem':          'Salem',
  'lucknow':        'Lucknow',
  'mysuru':         'Mysuru',
  'mysore':         'Mysuru',
  'jamshedpur':     'Jamshedpur',
  'goa':            'Goa',
  'indore':         'Indore',
  'nashik':         'Nashik',
  'nasik':          'Nashik',
  'sanand':         'Sanand',
  'silvassa':       'Silvassa',
  'aurangabad':     'Aurangabad',
  'kota':           'Kota',
  'vijayawada':     'Vijayawada',
  'anand':          'Anand',
  'belagavi':       'Belagavi',
  'belgaum':        'Belagavi',
  'bhopal':         'Bhopal',
  'chandigarh':     'Chandigarh',
  'gwalior':        'Gwalior',
  'kozhikode':      'Kozhikode',
  'calicut':        'Kozhikode',
  'mangalore':      'Mangalore',
  'madurai':        'Madurai',
  'tiruchirappalli': 'Tiruchirappalli',
  'trichy':         'Tiruchirappalli',
  'nagpur':         'Nagpur',
  'thane':          'Thane',
  'tirunelveli':    'Tirunelveli',
  'tirupati':       'Tirupati',
  'patna':          'Patna',
  'raipur':         'Raipur',
  'ghaziabad':      'Ghaziabad',
  'guntur':         'Guntur',
  'guwahati':       'Guwahati',
  'dhanbad':        'Dhanbad',
  'bokaro':         'Bokaro',
  'ernakulam':      'Ernakulam',
  'dharwad':        'Dharwad',
  'ajmer':          'Ajmer',
  'visakhapatnam':  'Visakhapatnam',
  'vizag':          'Visakhapatnam',
  'vadodara':       'Vadodara',
  'baroda':         'Vadodara',
  'surat':          'Surat',
  'gandhidham':     'Gandhidham',
  'trivandrum':     'Trivandrum',
  'thiruvananthapuram': 'Trivandrum',
  'mumbai ho':      'Mumbai',
  'mumbai (ho)':    'Mumbai',
  'navi mumbai':    'Mumbai',
  'remote':         'Remote',
  'none':           'None',
};
