import { createBrowserFetchSession } from '../shared/browserFetch.js'
import { extractTextFromPdfBuffer } from '../shared/pdfText.js'
import { extractJobFilterSignals } from '../../src/utils/jobFilterSignals.js'
import { normalizeScrapedJob } from './normalizeScrapedJob.js'

const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36'
const BROWSER_FALLBACK_WAIT_UNTIL = 'networkidle2'
const BROWSER_FALLBACK_SETTLE_TIME_MS = 3000
const DEFAULT_BROWSER_FALLBACK_SESSION_LIMIT = 4
const PDF_CONTENT_TYPE_PATTERN = /application\/pdf/i

const BLOCK_TAG_PATTERN = /<\/?(?:article|aside|blockquote|br|dd|div|dl|dt|figcaption|figure|footer|form|h[1-6]|header|hr|li|main|nav|ol|p|section|table|tbody|td|tfoot|th|thead|tr|ul)\b[^>]*>/gi
const SKIP_HOSTNAMES = new Set([
  'example.com',
  'www.example.com',
  'example.org',
  'www.example.org',
  'example.net',
  'www.example.net',
  'localhost',
  '127.0.0.1',
])

const decodeHtmlEntities = (value) => String(value ?? '')
  .replace(/&nbsp;/gi, ' ')
  .replace(/&amp;/gi, '&')
  .replace(/&quot;/gi, '"')
  .replace(/&#39;|&apos;/gi, "'")
  .replace(/&lt;/gi, '<')
  .replace(/&gt;/gi, '>')

const collapseSplitUppercaseHeadings = (value) => {
  let normalized = String(value ?? '')
  let previous = null

  while (normalized !== previous) {
    previous = normalized
    normalized = normalized.replace(/\b([A-Z])\s+([A-Z]{2,}\b)/g, '$1$2')
  }

  return normalized
}

const normalizeWhitespace = (value) => {
  if (value == null) return null

  const normalized = collapseSplitUppercaseHeadings(decodeHtmlEntities(value))
    .replace(/\u00a0/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

  return normalized || null
}

const normalizeExistingPublicEvidenceValue = (value) => normalizeWhitespace(
  String(value ?? '')
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi, ' ')
    .replace(BLOCK_TAG_PATTERN, '\n')
    .replace(/<[^>]+>/g, ' '),
)

const GENERIC_PUBLIC_JOB_SHELL_PATTERNS = [
  /\bgroup of locations\b/i,
  /\bcopy to clipboard\b/i,
  /\bsimilar jobs\b/i,
  /\bwork summary\b/i,
  /\bthis summary is generated by ai assist\b/i,
  /\bare you still with us\b/i,
  /\bbe the first to apply\b/i,
  /\bcareers loaded\b/i,
]

const TRAILING_JOB_SITE_CHROME_PATTERNS = [
  /\bapply now\b/i,
  /\bjob info\b/i,
  /\bcopy to clipboard\b/i,
  /\bsimilar jobs\b/i,
  /\bi am an employee\b/i,
  /\bpage [a-z0-9 .'"()_-]{0,120} loaded\b/i,
]

const JOB_SPECIFIC_APPLY_FLOW_PATTERNS = [
  /\bapply now\b/i,
  /\beasy apply\b/i,
  /\bstart your application\b/i,
  /\bpersonal information\b/i,
  /\bresume\b/i,
  /\bupload resume\b/i,
  /\bjob identification\b/i,
  /\bposting date\b/i,
  /\bapply before\b/i,
  /\bjob schedule\b/i,
  /\bjob category\b/i,
  /\bdegree level\b/i,
  /\blocations?\b/i,
  /\baddress\b/i,
]

const JOB_METADATA_SHELL_PATTERNS = [
  /\bjob snapshot\b/i,
  /\bjob id\b/i,
  /\bemployee type\b/i,
  /\bupdated date\b/i,
  /\bdepartment\b/i,
  /\bwork location\b/i,
  /\bbusiness unit\b/i,
  /\bfunction\b/i,
  /\bbranch\b/i,
  /\breference no\.?\b/i,
  /\brequisition id\b/i,
  /\bjob requisition id\b/i,
  /\bjob req id\b/i,
  /\bposting date\b/i,
  /\bjob schedule\b/i,
  /\bemployee status\b/i,
  /\bposition type\b/i,
  /\bcountry\/region\b/i,
]

const NO_DESCRIPTION_PLACEHOLDER_PATTERNS = [
  /\bno job description at the moment\b/i,
  /\bif the details spark your interest, feel free to go ahead and apply\b/i,
]

const GENERIC_JOB_SUMMARY_PATTERN = /\b(?:career|careers|job|jobs|apply|application|portal|opening|openings)\b/i

const EMPTY_SECTION_HEADING_TEMPLATE_LABELS = [
  'job objective',
  'essential job tasks',
  'areas of responsibility',
  'required qualifications',
  'work experience',
  'languages needed in position',
  'key interfaces- external',
  'key interfaces- internal',
  'behavioural competencies',
  'equal opportunities employment',
]

const looksLikeEmptySectionHeadingTemplate = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false

  const lowercase = normalized.toLowerCase()
  const matchedLabelRanges = EMPTY_SECTION_HEADING_TEMPLATE_LABELS
    .map((label) => {
      const index = lowercase.indexOf(label)
      return index === -1 ? null : [index, index + label.length]
    })
    .filter(Boolean)

  if (
    matchedLabelRanges.length < 6
    || !lowercase.includes('job objective')
    || !lowercase.includes('work experience')
    || !lowercase.includes('behavioural competencies')
  ) {
    return false
  }

  matchedLabelRanges.sort((left, right) => left[0] - right[0])
  const firstIndex = matchedLabelRanges[0][0]
  const lastIndex = matchedLabelRanges[matchedLabelRanges.length - 1][1]
  const clusteredText = lowercase.slice(firstIndex, lastIndex)
  const sentencePunctuationCount = (clusteredText.match(/[.:;](?=\s|$)/g) || []).length

  return (lastIndex - firstIndex) <= 420 && sentencePunctuationCount <= 2
}

const looksLikeAmritaCampusShell = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false

  const lowercase = normalized.toLowerCase()
  const campusLabelMatches = lowercase.match(/\bcampus:\s*[a-z]/g) || []
  const exploreCampusMatches = lowercase.match(
    /\bexplore\s+(?:amaravati|amritapuri|bengaluru|chennai|coimbatore|kochi|mysuru|nagercoil)\b/g,
  ) || []

  return lowercase.includes('requirements of future employers')
    && lowercase.includes('amrita vishwa vidyapeetham')
    && (campusLabelMatches.length >= 2 || exploreCampusMatches.length >= 3)
}

const NAGARRO_MOTIVATIONAL_SHELL_PHRASES = [
  'by this point in your career, it is not just about the tech you know or how well you can code',
  'you have begun to prove your worth in our industry',
  'at nagarro, we love breaking new ground and doing unprecedented stuff',
]

const RESULT_NOTICE_SHELL_PATTERNS = [
  /\bnotice regarding list of provisionally shortlisted candidates\b/i,
  /\bprovisionally shortlisted candidates\b/i,
  /\bshortlisted candidates\b/i,
  /\binterview call letters?\b/i,
  /\binterview schedule\b/i,
  /\bappear in interview\b/i,
  /\bfinal result\b/i,
]

const looksLikeNagarroMotivationalShell = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false

  const lowercase = normalized.toLowerCase()
  return NAGARRO_MOTIVATIONAL_SHELL_PHRASES.some((phrase) => lowercase.includes(phrase))
}

const looksLikeResultNoticeShell = (value) => countPatternHits(
  RESULT_NOTICE_SHELL_PATTERNS,
  value,
) >= 1

const looksLikeBlockingPublicJobShell = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false
  if (/\bpage not found\b/i.test(normalized)) return true
  if (/\byou do not have access to this page\b/i.test(normalized)) return true
  if (/\binvalid url argument\b/i.test(normalized)) return true
  if (looksLikeResultNoticeShell(normalized)) return true
  if (looksLikeEmptySectionHeadingTemplate(normalized)) return true
  if (looksLikeAmritaCampusShell(normalized)) return true
  return false
}

const looksLikeHardGenericPublicJobShell = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false
  if (looksLikeBlockingPublicJobShell(normalized)) return true
  if (looksLikeNagarroMotivationalShell(normalized)) return true
  return false
}

const looksLikeGenericPublicJobShell = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false
  if (looksLikeHardGenericPublicJobShell(normalized)) return true

  let matchedSignals = 0
  for (const pattern of GENERIC_PUBLIC_JOB_SHELL_PATTERNS) {
    if (!pattern.test(normalized)) continue
    matchedSignals += 1
    if (matchedSignals >= 2) return true
  }

  return false
}

const looksLikeTruncatedPublicPreview = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false

  return normalized.length <= 220 && /(?:\.\.\.|…)\s*$/.test(normalized)
}

const AVATURE_TRANSIENT_BROWSER_SHELL_MARKERS = [
  'Skip to content',
  'Apply now',
  'Required education',
  'Your role and responsibilities',
]

const looksLikeTransientBrowserRenderShell = (html, jobUrl = '') => {
  const rawHtml = String(html ?? '')
  if (!rawHtml) return false

  if (/(?:awswafcookiedomainlist|gokuprops|challenge\.js)/i.test(rawHtml)) {
    return true
  }

  const normalizedJobUrl = String(jobUrl ?? '')
  const looksLikeAvatureJobDetailShell =
    /avature\.portal\.page/i.test(rawHtml)
    && /(?:\/|^)JobDetail(?:[/?-]|$)/i.test(rawHtml + normalizedJobUrl)

  if (!looksLikeAvatureJobDetailShell) {
    return false
  }

  if (rawHtml.length >= 20000) {
    return false
  }

  return !AVATURE_TRANSIENT_BROWSER_SHELL_MARKERS.some((marker) => rawHtml.includes(marker))
}

const shouldWarmBrowserFallbackSession = (url) => {
  try {
    const parsed = new URL(String(url ?? ''))
    return parsed.hostname.toLowerCase() === 'careers.ibm.com'
      && /\/careers\/JobDetail/i.test(parsed.pathname)
  } catch {
    return false
  }
}

const hasSufficientPublicJobEvidence = (job = {}) => !shouldRefreshPublicJobEvidence(job)

const getExistingPublicEvidenceParts = (job = {}) => (
  [
    job.description,
    job.jobDescription,
    job.minimumQualification,
    job.preferredQualification,
  ]
    .map((value) => normalizeExistingPublicEvidenceValue(value))
    .filter(Boolean)
    .filter((value, index, values) => values.indexOf(value) === index)
)

const buildExistingPublicEvidence = (job = {}) => {
  const normalizedJob = normalizeScrapedJob(job, {
    source: job.source || null,
  })
  const experienceText = normalizeWhitespace(normalizedJob.experienceRequired)
  const descriptionText = normalizeWhitespace(
    getExistingPublicEvidenceParts(normalizedJob).join(' '),
  )
  const hasRichDescription = Boolean(
    descriptionText
    && descriptionText.length >= 200
    && !looksLikeGenericPublicJobShell(descriptionText),
  )

  return {
    experienceText,
    descriptionText,
    hasRichDescription,
  }
}

const shouldRefreshPublicJobEvidence = (job = {}) => {
  const {
    experienceText,
    descriptionText,
    hasRichDescription,
  } = buildExistingPublicEvidence(job)
  const hasProviderVerifiedPublicEvidence =
    job.publicExperienceChecked === true
    && descriptionText
    && !looksLikeGenericPublicJobShell(descriptionText)
    && !looksLikeTruncatedPublicPreview(descriptionText)

  if (hasProviderVerifiedPublicEvidence) return false
  if (experienceText && hasRichDescription) return false

  if (!experienceText) return true
  return !descriptionText || descriptionText.length < 200
}

const escapeRegex = (value) => String(value ?? '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const extractFirst = (pattern, value) => {
  const match = pattern.exec(String(value ?? ''))
  return match ? match[1] : null
}

const extractAttributeValue = (tag, attributeName) => {
  const escapedName = escapeRegex(attributeName)
  const doubleQuoted = extractFirst(new RegExp(`${escapedName}\\s*=\\s*"([^"]*)"`, 'i'), tag)
  if (doubleQuoted != null) return normalizeWhitespace(doubleQuoted)

  const singleQuoted = extractFirst(new RegExp(`${escapedName}\\s*=\\s*'([^']*)'`, 'i'), tag)
  if (singleQuoted != null) return normalizeWhitespace(singleQuoted)

  return null
}

const extractMetaContent = (key, html) => {
  for (const match of String(html ?? '').matchAll(/<meta\b[^>]*>/gi)) {
    const tag = match[0]
    const property = extractAttributeValue(tag, 'property')
    const name = extractAttributeValue(tag, 'name')

    if (property !== key && name !== key) {
      continue
    }

    const content = extractAttributeValue(tag, 'content')
    if (content) {
      return content
    }
  }

  return null
}

const extractTitle = (html) => normalizeWhitespace(
  extractMetaContent('og:title', html)
    || extractFirst(/<title[^>]*>\s*([\s\S]*?)\s*<\/title>/i, html),
)

const extractPageSummary = (html) => normalizeWhitespace(
  extractMetaContent('og:description', html)
    || extractMetaContent('description', html),
)

const stripHtmlToText = (html) => normalizeWhitespace(
  String(html ?? '')
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi, ' ')
    .replace(BLOCK_TAG_PATTERN, '\n')
    .replace(/<[^>]+>/g, ' '),
)

const extractLabeledExperience = (text) => {
  const normalized = normalizeWhitespace(text)
  if (!normalized) return null

  const experienceProfile = extractJobFilterSignals({
    description: normalized,
  })?.experienceProfile
  const evidence = normalizeWhitespace(experienceProfile?.evidence)

  if (!evidence || experienceProfile?.confidence !== 'high') {
    return null
  }

  return (
    (
      experienceProfile.minimumYears === 0
      && experienceProfile.maximumYears === 0
    )
      ? 'No experience required'
      : evidence
  )
}

const RELEVANT_JOB_CONTENT_PATTERN = /\b(job description|job summary|about job|about the role|qualifications?|requirements?|responsibilities|required skills|preferred qualifications?|preferred experience|expertise|what will you do|what are we looking for|key job details|what you bring|roles?\s*&\s*responsibilities|key skills required|functional area|must-?have skills?|nice to have|key responsibilities|role overview|role objective|reporting to|technical skills|education mandatory|minimum eligibility|eligibility|organization|title\s*&\s*(?:no|number)\s*of posts|term of appointment|scale of pay|specific requirements|service(?:\/department)?|duration)\b/i

const trimTrailingJobSiteChrome = (value) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return null

  let cutoffIndex = normalized.length
  for (const pattern of TRAILING_JOB_SITE_CHROME_PATTERNS) {
    const match = pattern.exec(normalized)
    if (!match || match.index <= 40) continue
    cutoffIndex = Math.min(cutoffIndex, match.index)
  }

  return normalizeWhitespace(normalized.slice(0, cutoffIndex)) || normalized
}

const extractRelevantJobSectionText = (pageText) => {
  const normalized = normalizeWhitespace(pageText)
  if (!normalized) return null

  const match = RELEVANT_JOB_CONTENT_PATTERN.exec(normalized)
  if (!match) return null

  return trimTrailingJobSiteChrome(normalized.slice(match.index))
}

const hasRelevantJobContent = (pageText) => RELEVANT_JOB_CONTENT_PATTERN.test(pageText || '')

const getExistingDescriptionEvidence = (job = {}) => (
  getExistingPublicEvidenceParts(job)
    .join('\n\n')
)

const normalizeComparablePageUrl = (value) => {
  try {
    const parsed = new URL(String(value ?? ''))
    parsed.hash = ''
    const normalized = parsed.toString().replace(/\/$/, '')
    return normalized || null
  } catch {
    return null
  }
}

const SHARED_CAREERS_LISTING_SEGMENTS = new Set([
  'career',
  'careers',
  'apply-now',
  'current-opening',
  'current-openings',
  'job-opening',
  'job-openings',
  'jobs',
  'join-us',
  'openings',
  'vacancies',
  'vacancy',
  'work-with-us',
])

const isSharedCareersAtsPlatform = (value) => {
  const normalized = String(value ?? '').trim().toLowerCase()
  return !normalized
    || normalized.startsWith('official-company-careers')
    || normalized === 'official-first-party-current-openings-page'
    || normalized === 'official-first-party-static-careers-page'
}

const looksLikeSharedCareersListingUrl = (value) => {
  try {
    const parsed = new URL(String(value ?? ''))
    const pathname = parsed.pathname.toLowerCase()
    if (
      /(?:^|\/)(?:apply-now|career|careers|current[_-]?openings?|job[_-]?openings?|jobs|join-us(?:-\d+)?|openings|vacanc(?:y|ies)|work-with-us)(?:\.html?)?$/i.test(pathname)
    ) {
      return true
    }

    const pathnameSegments = pathname
      .split('/')
      .map((segment) => segment.trim())
      .filter(Boolean)
    const lastSegment = pathnameSegments[pathnameSegments.length - 1]
      ?.replace(/\.html?$/i, '')
      ?.replace(/[_-]+/g, '-')
    return Boolean(lastSegment && SHARED_CAREERS_LISTING_SEGMENTS.has(lastSegment))
  } catch {
    return false
  }
}

const looksLikePublicApplicationHandoffUrl = (value) => {
  try {
    const parsed = new URL(String(value ?? ''))
    const hostname = parsed.hostname.toLowerCase()
    const pathname = parsed.pathname.toLowerCase()
    if (hostname === 'forms.gle') return true
    if (hostname === 'docs.google.com' && pathname.startsWith('/forms/')) return true
    if (hostname.endsWith('.typeform.com') || hostname === 'typeform.com') return true
    if (hostname.endsWith('.jotform.com') || hostname === 'jotform.com') return true
    return false
  } catch {
    return false
  }
}

const looksLikeThinApplyShellUrl = (value) => {
  try {
    const parsed = new URL(String(value ?? ''))
    const pathname = parsed.pathname.toLowerCase()
    return /\/login(?:\/|$)/i.test(pathname)
      || /\/oneclick-ui\//i.test(pathname)
  } catch {
    return false
  }
}

const looksLikeHostedJobDetailUrl = (value) => {
  try {
    const parsed = new URL(String(value ?? ''))
    const hostname = parsed.hostname.toLowerCase()
    const pathname = parsed.pathname.toLowerCase()
    if (/skillate\.com$/i.test(hostname) && /^\/jobs\/[^/]+/i.test(pathname)) return true
    if (/zappyhire\.com$/i.test(hostname) && /\/apply$/i.test(pathname) && parsed.searchParams.get('job')) return true
    return false
  } catch {
    return false
  }
}

const looksLikeSharedCareersListingDescription = (value, title = null) => {
  const normalized = normalizeWhitespace(value)
  if (!normalized) return false

  const hasCurrentOpeningsSignals =
    /\bcurrent openings\b/i.test(normalized)
    && (
      /\bselect the team\b/i.test(normalized)
      || /\bselect the location\b/i.test(normalized)
      || (/\bteam\s*:/i.test(normalized) && /\blocation\s*:/i.test(normalized))
    )
  if (hasCurrentOpeningsSignals) return true

  const normalizedTitle = normalizeWhitespace(title)
  return Boolean(
    normalizedTitle
    && /\bofficial\b/i.test(normalized)
    && /\bopening published on the first-party apply form\b/i.test(normalized)
    && textContainsComparable(normalized, normalizedTitle),
  )
}

const isSamePublicPage = (left, right) => {
  const normalizedLeft = normalizeComparablePageUrl(left)
  const normalizedRight = normalizeComparablePageUrl(right)
  return Boolean(normalizedLeft && normalizedRight && normalizedLeft === normalizedRight)
}

const hasVerifiedExistingPublicDescription = (job = {}) => {
  const descriptionText = getExistingDescriptionEvidence(job)
  if (!descriptionText || descriptionText.length < 200) return false
  if (looksLikeGenericPublicJobShell(descriptionText)) return false
  if (looksLikeMultiJobListingPage(descriptionText)) return false
  return hasRelevantJobContent(descriptionText) || Boolean(extractLabeledExperience(descriptionText))
}

const hasVerifiedListingOnlyPublicSurface = (job = {}) => {
  const normalizedJob = normalizeScrapedJob(job, {
    source: job.source || null,
  })
  if (!isSharedCareersAtsPlatform(normalizedJob.atsPlatform)) return false
  if (!normalizedJob.title) return false

  const descriptionText = getExistingDescriptionEvidence(normalizedJob)
  const listingPageUrl = String(normalizedJob.companyCareerPage ?? normalizedJob.sourceUrl ?? '').trim()
  const hasSharedListingSurface =
    looksLikeSharedCareersListingUrl(listingPageUrl)
    || looksLikeSharedCareersListingDescription(descriptionText, normalizedJob.title)
  if (!hasSharedListingSurface) return false

  const applyUrl = String(normalizedJob.applyUrl ?? normalizedJob.sourceUrl ?? '').trim()
  const applyStaysOnListingPage = /^mailto:/i.test(applyUrl)
    || isSamePublicPage(applyUrl, listingPageUrl)
    || looksLikePublicApplicationHandoffUrl(applyUrl)
  if (!applyStaysOnListingPage) return false

  return !extractLabeledExperience(descriptionText)
}

const promoteExistingPublicEvidence = (job = {}) => {
  if (job.publicExperienceChecked === true) return job

  if (hasVerifiedExistingPublicDescription(job)) {
    return {
      ...job,
      publicExperienceChecked: true,
    }
  }

  if (hasVerifiedListingOnlyPublicSurface(job)) {
    return {
      ...job,
      publicExperienceChecked: true,
    }
  }

  return job
}

const preserveListingOnlyPublicVerification = (originalJob = {}, baseJob = {}, candidateJob = {}) => {
  if (candidateJob.publicExperienceChecked === true) return candidateJob
  if (
    !normalizeWhitespace(candidateJob.experienceRequired)
    && hasVerifiedListingOnlyPublicSurface(candidateJob)
  ) {
    return {
      ...candidateJob,
      publicExperienceChecked: true,
    }
  }
  if (baseJob.publicExperienceChecked !== true) return candidateJob
  if (
    originalJob.publicExperienceChecked !== true
    && !normalizeWhitespace(candidateJob.experienceRequired)
  ) {
    return {
      ...candidateJob,
      publicExperienceChecked: true,
    }
  }
  if (!hasVerifiedListingOnlyPublicSurface(candidateJob)) return candidateJob
  return {
    ...candidateJob,
    publicExperienceChecked: true,
  }
}

const extractPrimaryHeading = (html) => normalizeWhitespace(
  extractFirst(/<h1[^>]*>\s*([\s\S]*?)\s*<\/h1>/i, html)
    || extractFirst(/<h2[^>]*>\s*([\s\S]*?)\s*<\/h2>/i, html)
    || extractFirst(/<h3[^>]*>\s*([\s\S]*?)\s*<\/h3>/i, html),
)

const normalizeComparableText = (value) => normalizeWhitespace(value)
  ?.toLowerCase()
  .replace(/[^a-z0-9]+/g, ' ')
  .trim()
  || null

const findComparableTextIndex = (haystack, needle) => {
  const normalizedHaystack = normalizeComparableText(haystack)
  const normalizedNeedle = normalizeComparableText(needle)
  if (!normalizedHaystack || !normalizedNeedle) return -1
  return normalizedHaystack.indexOf(normalizedNeedle)
}

const textContainsComparable = (haystack, needle) => {
  return findComparableTextIndex(haystack, needle) !== -1
}

const countMatches = (pattern, value) => {
  const matches = String(value ?? '').match(pattern)
  return matches ? matches.length : 0
}

const countPatternHits = (patterns, value) => patterns.reduce(
  (total, pattern) => total + (pattern.test(String(value ?? '')) ? 1 : 0),
  0,
)

const looksLikeNoDescriptionPlaceholder = (value) => countPatternHits(
  NO_DESCRIPTION_PLACEHOLDER_PATTERNS,
  value,
) >= 1

const looksLikeMultiJobListingPage = (pageText) => {
  const normalized = normalizeWhitespace(pageText)
  if (!normalized) return false

  return /\bcurrent openings\b/i.test(normalized)
    && /\bRole\b/i.test(normalized)
    && /\bJob Details Apply\b/i.test(normalized)
}

const defaultFetchText = async (url) => {
  const response = await fetch(url, {
    headers: {
      'User-Agent': USER_AGENT,
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    },
  })

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} for ${url}`)
  }

  const contentType = response.headers?.get?.('content-type') || ''
  if (PDF_CONTENT_TYPE_PATTERN.test(contentType) || /\.pdf(?:$|\?)/i.test(String(url))) {
    return extractTextFromPdfBuffer(await response.arrayBuffer())
  }

  return response.text()
}

const shouldSkipDefaultFetch = (jobUrl) => {
  try {
    const parsed = new URL(jobUrl)
    return SKIP_HOSTNAMES.has(parsed.hostname.toLowerCase()) || parsed.hostname.endsWith('.example')
  } catch {
    return true
  }
}

const toAbsoluteUrl = (value, baseUrl = null) => {
  try {
    return new URL(String(value ?? ''), baseUrl || undefined).toString()
  } catch {
    return null
  }
}

const shouldPreferApplyUrl = (job = {}) => {
  const applyUrl = normalizeWhitespace(job.applyUrl)
  const sourceUrl = normalizeWhitespace(job.sourceUrl)
  if (!applyUrl) return false
  if (!sourceUrl) return true
  if (isSamePublicPage(applyUrl, sourceUrl)) return false
  if (looksLikeThinApplyShellUrl(applyUrl)) return false
  if (looksLikeHostedJobDetailUrl(applyUrl)) return true
  return looksLikeSharedCareersListingUrl(sourceUrl)
    && !/^mailto:/i.test(applyUrl)
    && !looksLikePublicApplicationHandoffUrl(applyUrl)
}

export const resolvePublicJobUrl = (job = {}) => {
  const sourceUrl = normalizeWhitespace(job.sourceUrl)
  const applyUrl = normalizeWhitespace(job.applyUrl)
  const link = normalizeWhitespace(job.link)
  if (shouldPreferApplyUrl(job)) return applyUrl || sourceUrl || link || null
  return sourceUrl || applyUrl || link || null
}

const isEmbeddedGreenhouseJobUrl = (jobUrl) => {
  try {
    const parsed = new URL(jobUrl)
    const hostname = parsed.hostname.toLowerCase()
    return (
      (hostname === 'boards.greenhouse.io' || hostname === 'job-boards.greenhouse.io')
      && /\/[a-z0-9-]+\/jobs\/\d+/i.test(parsed.pathname)
    )
  } catch {
    return false
  }
}

const extractEmbeddedPublicJobUrl = (html, baseUrl = null) => {
  for (const match of String(html ?? '').matchAll(/<iframe\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi)) {
    const candidateUrl = toAbsoluteUrl(match[1], baseUrl)
    if (candidateUrl && isEmbeddedGreenhouseJobUrl(candidateUrl)) {
      return candidateUrl
    }
  }

  return null
}

const isSmartRecruitersPublicJobUrl = (jobUrl) => {
  try {
    return new URL(jobUrl).hostname.toLowerCase() === 'jobs.smartrecruiters.com'
  } catch {
    return false
  }
}

export const inferExperienceFromPublicPageHtml = (job = {}, html) => {
  const publicJobUrl = resolvePublicJobUrl(job)
  const pageText = stripHtmlToText(html)
  const trimmedPageText = trimTrailingJobSiteChrome(pageText) || pageText
  const pageSummary = extractPageSummary(html)
  const pageTitle = extractTitle(html)
  const primaryHeading = extractPrimaryHeading(html)
  const smartRecruitersJobAdId = extractMetaContent('sr:job-ad-id', html)
  const explicitExperience = extractLabeledExperience(pageText)
  const pageTextHasBlockingGenericShell = looksLikeBlockingPublicJobShell(pageText)
  const pageTextHasHardGenericShell = looksLikeHardGenericPublicJobShell(pageText)
  const pageTextHasSmartRecruitersMotivationalShell =
    looksLikeNagarroMotivationalShell(pageText)
    && isSmartRecruitersPublicJobUrl(publicJobUrl)
  const pageTextLooksLikeGenericShell = looksLikeGenericPublicJobShell(pageText)
  const pageSummaryLooksLikeGenericShell = looksLikeGenericPublicJobShell(pageSummary)
  const relevantPageText = hasRelevantJobContent(pageText) || explicitExperience
    ? (extractRelevantJobSectionText(pageText) || pageText)
    : null
  const relevantPageSummary = hasRelevantJobContent(pageSummary)
    ? (extractRelevantJobSectionText(pageSummary) || pageSummary)
    : null
  const relevantPageTextLooksLikeGenericShell = looksLikeGenericPublicJobShell(relevantPageText)
  const relevantPageSummaryLooksLikeGenericShell = looksLikeGenericPublicJobShell(relevantPageSummary)
  const relevantPageTextLooksLikeNoDescriptionPlaceholder =
    looksLikeNoDescriptionPlaceholder(relevantPageText)
  const hasJobSpecificPageTitle =
    textContainsComparable(pageTitle, job.title)
    || textContainsComparable(primaryHeading, job.title)
  const bodyTitleMatchIndex = findComparableTextIndex(trimmedPageText, job.title)
  const hasJobSpecificVisibleTitle = Boolean(
    hasJobSpecificPageTitle
    || (bodyTitleMatchIndex !== -1 && bodyTitleMatchIndex <= 220)
  )
  const hasJobSpecificMetaSummary = Boolean(
    hasJobSpecificPageTitle
    && pageSummary
    && pageSummary.length >= 10
    && !pageSummaryLooksLikeGenericShell
    && !GENERIC_JOB_SUMMARY_PATTERN.test(pageSummary)
  )
  const hasSmartRecruitersJobMetadata = Boolean(
    hasJobSpecificPageTitle
    && isSmartRecruitersPublicJobUrl(publicJobUrl)
    && smartRecruitersJobAdId
  )
  const hasJobSpecificApplyFlowEvidence = Boolean(
    hasJobSpecificVisibleTitle
    && !pageTextHasBlockingGenericShell
    && countPatternHits(JOB_SPECIFIC_APPLY_FLOW_PATTERNS, pageText) >= 2
  )
  const hasStructuredJobMetadataShell = Boolean(
    hasJobSpecificVisibleTitle
    && !pageTextHasBlockingGenericShell
    && countPatternHits(JOB_METADATA_SHELL_PATTERNS, pageText) >= 3
    && looksLikeNoDescriptionPlaceholder(pageText)
  )
  const hasGenericListingShell = looksLikeMultiJobListingPage(pageText)
  const hasRelevantPublicEvidence = !pageTextHasHardGenericShell && Boolean(
    explicitExperience
    || (
      relevantPageText
      && !relevantPageTextLooksLikeGenericShell
      && !relevantPageTextLooksLikeNoDescriptionPlaceholder
    )
    || (
      relevantPageSummary
      && !pageSummaryLooksLikeGenericShell
      && !relevantPageSummaryLooksLikeGenericShell
    )
  )
  const hasUsablePublicEvidence = Boolean(
    hasRelevantPublicEvidence
    || hasJobSpecificMetaSummary
  )
  const hasVerifiedPublicJobEvidence = Boolean(
    explicitExperience
    || (
      hasJobSpecificVisibleTitle
      && (
        hasRelevantPublicEvidence
        || hasJobSpecificMetaSummary
        || hasJobSpecificApplyFlowEvidence
        || pageTextHasSmartRecruitersMotivationalShell
        || hasSmartRecruitersJobMetadata
        || hasStructuredJobMetadataShell
      )
    ),
  )
  const preferredPublicTitle =
    (textContainsComparable(primaryHeading, job.title) ? primaryHeading : null)
    || (textContainsComparable(pageTitle, job.title) ? pageTitle : null)
    || null
  const retainedExistingDescriptionParts = [job.description, job.jobDescription]
    .map((value) => normalizeWhitespace(value))
    .filter((value) => value && !looksLikeGenericPublicJobShell(value))
    .filter((value) => job.publicExperienceChecked !== true || value.length >= 200)
  const retainedExistingDescription = retainedExistingDescriptionParts.join('\n\n') || null
  const hasTrustedPriorPublicEvidence =
    job.publicExperienceChecked === true
    && retainedExistingDescriptionParts.length > 0
  const composedPublicDescription = [
    ...retainedExistingDescriptionParts,
    hasJobSpecificMetaSummary
      ? pageSummary
      : (
          pageSummaryLooksLikeGenericShell || relevantPageSummaryLooksLikeGenericShell
            ? null
            : relevantPageSummary
        ),
    hasGenericListingShell
    || pageTextHasHardGenericShell
    || relevantPageTextLooksLikeGenericShell
    || relevantPageTextLooksLikeNoDescriptionPlaceholder
    || hasStructuredJobMetadataShell
      ? null
      : relevantPageText,
  ]
    .map((value) => normalizeWhitespace(value))
    .filter(Boolean)
    .join('\n\n') || null

  const normalized = normalizeScrapedJob({
    ...job,
    title: hasUsablePublicEvidence && hasJobSpecificPageTitle ? (preferredPublicTitle || job.title) : job.title,
    experienceRequired: job.experienceRequired || explicitExperience,
    description: composedPublicDescription,
    jobDescription: composedPublicDescription,
  }, {
    source: job.source || null,
  })

  return {
    ...job,
    title: normalized.title,
    description: normalized.jobDescription || retainedExistingDescription || null,
    jobDescription: normalized.jobDescription
      || retainedExistingDescription
      || relevantPageSummary
      || null,
    experienceRequired: normalized.experienceRequired,
    publicExperienceChecked: hasTrustedPriorPublicEvidence || hasVerifiedPublicJobEvidence,
  }
}

export const enrichJobWithPublicExperience = async (job = {}, {
  fetchText = null,
  fetchBrowserText = null,
  getBrowserText = null,
} = {}) => {
  const promotedJob = promoteExistingPublicEvidence(job)
  if (!shouldRefreshPublicJobEvidence(promotedJob)) return promotedJob

  const jobUrl = resolvePublicJobUrl(promotedJob)
  if (!jobUrl) return promotedJob

  const fetchImpl = fetchText || defaultFetchText
  const canUseDefaultFetch = !fetchText && !shouldSkipDefaultFetch(jobUrl)
  const canUseBrowserFetch = Boolean(fetchBrowserText || getBrowserText)
  if (!fetchText && !canUseDefaultFetch && !canUseBrowserFetch) return promotedJob

  let enriched = promotedJob
  let rawFetchedHtml = null
  try {
    if (fetchText || canUseDefaultFetch) {
      rawFetchedHtml = await fetchImpl(jobUrl)
      enriched = inferExperienceFromPublicPageHtml(promotedJob, rawFetchedHtml)
    }
  } catch {
    enriched = promotedJob
  }

  const embeddedPublicJobUrl = rawFetchedHtml
    ? extractEmbeddedPublicJobUrl(rawFetchedHtml, jobUrl)
    : null
  if (
    embeddedPublicJobUrl
    && embeddedPublicJobUrl !== jobUrl
    && !hasSufficientPublicJobEvidence(enriched)
  ) {
    try {
      const embeddedHtml = await fetchImpl(embeddedPublicJobUrl)
      enriched = inferExperienceFromPublicPageHtml({
        ...enriched,
        sourceUrl: embeddedPublicJobUrl,
        applyUrl: embeddedPublicJobUrl,
        link: embeddedPublicJobUrl,
      }, embeddedHtml)
    } catch {
      // Keep the wrapper-page result when the embedded board cannot be fetched.
    }
  }

  enriched = preserveListingOnlyPublicVerification(job, promotedJob, enriched)

  if (hasSufficientPublicJobEvidence(enriched) || !canUseBrowserFetch) {
    return enriched
  }

  // Preserve newly verified public pages that legitimately omit experience and
  // don't expose richer job text; an empty browser fallback should not
  // downgrade those raw-fetch verifications.
  if (
    enriched.publicExperienceChecked === true
    && promotedJob.publicExperienceChecked !== true
    && !normalizeWhitespace(enriched.description)
    && !normalizeWhitespace(enriched.jobDescription)
  ) {
    return enriched
  }

  try {
    const browserFetchImpl = fetchBrowserText || await getBrowserText?.()
    if (!browserFetchImpl) return enriched

    const browserHtml = await browserFetchImpl(jobUrl)
    let browserEnriched = inferExperienceFromPublicPageHtml(enriched, browserHtml)

    if (
      !hasSufficientPublicJobEvidence(browserEnriched)
      && looksLikeTransientBrowserRenderShell(browserHtml, jobUrl)
    ) {
      const retriedBrowserHtml = await browserFetchImpl(jobUrl)
      browserEnriched = inferExperienceFromPublicPageHtml(browserEnriched, retriedBrowserHtml)
    }

    return preserveListingOnlyPublicVerification(job, promotedJob, browserEnriched)
  } catch {
    return enriched
  }
}

export const enrichJobsWithPublicExperience = async (jobs = [], options = {}) => {
  const concurrency = Math.max(1, Number.isInteger(options.concurrency) ? options.concurrency : 4)
  const results = new Array(jobs.length)
  let cursor = 0
  let browserFallback = null

  const getBrowserFallback = async () => {
    if (options.fetchBrowserText) {
      return {
        fetchBrowserText: options.fetchBrowserText,
        close: async () => {},
      }
    }

    if (options.useBrowserFallback === false) {
      return null
    }

    if (browserFallback) return browserFallback

    const browserFallbackSessionCount = Math.max(
      1,
      Math.min(
        jobs.length,
        concurrency,
        Number.isInteger(options.browserFallbackConcurrency)
          ? Math.max(1, options.browserFallbackConcurrency)
          : DEFAULT_BROWSER_FALLBACK_SESSION_LIMIT,
      ),
    )
    const sessions = await Promise.all(
      Array.from({ length: browserFallbackSessionCount }, () => createBrowserFetchSession({
        userAgent: USER_AGENT,
        timeoutMs: 60000,
        waitUntil: BROWSER_FALLBACK_WAIT_UNTIL,
        settleTimeMs: BROWSER_FALLBACK_SETTLE_TIME_MS,
      })),
    )
    const queues = sessions.map(() => Promise.resolve())
    const warmedUrlsBySession = sessions.map(() => new Set())
    let sessionCursor = 0

    const fetchBrowserText = (url) => {
      const sessionIndex = sessionCursor % sessions.length
      sessionCursor += 1
      const next = queues[sessionIndex].then(
        async () => {
          if (
            shouldWarmBrowserFallbackSession(url)
            && !warmedUrlsBySession[sessionIndex].has(url)
          ) {
            await sessions[sessionIndex].fetchPage(url)
            warmedUrlsBySession[sessionIndex].add(url)
          }

          return sessions[sessionIndex].fetchText(url)
        },
        async () => {
          if (
            shouldWarmBrowserFallbackSession(url)
            && !warmedUrlsBySession[sessionIndex].has(url)
          ) {
            await sessions[sessionIndex].fetchPage(url)
            warmedUrlsBySession[sessionIndex].add(url)
          }

          return sessions[sessionIndex].fetchText(url)
        },
      )
      queues[sessionIndex] = next.catch(() => {})
      return next
    }

    browserFallback = {
      fetchBrowserText,
      close: async () => {
        await Promise.allSettled(sessions.map((session) => session.close()))
      },
    }

    return browserFallback
  }

  const worker = async () => {
    while (cursor < jobs.length) {
      const currentIndex = cursor
      cursor += 1
      results[currentIndex] = await enrichJobWithPublicExperience(jobs[currentIndex], {
        ...options,
        fetchBrowserText: options.fetchBrowserText || null,
        getBrowserText: options.fetchBrowserText
          ? null
          : async () => {
              const browserHandler = await getBrowserFallback()
              return browserHandler?.fetchBrowserText || null
            },
      })
    }
  }

  try {
    await Promise.all(
      Array.from({ length: Math.min(concurrency, jobs.length) }, () => worker()),
    )
  } finally {
    if (browserFallback) {
      await browserFallback.close()
    }
  }

  return results
}
