import assert from 'node:assert/strict'
import test from 'node:test'

const loadAavishkarModule = async () => {
  try {
    return await import('../aavishkar/script.js')
  } catch {
    assert.fail('Expected Aavishkar scraper module at ../aavishkar/script.js')
  }
}

const homepageHtml = `
<!doctype html>
<html lang="en">
  <head>
    <title>Aavishkaar Group: One of the largest Impact Platforms across the Global South</title>
    <meta name="description" content="We exist to bridge the opportunity gap for the emerging 3 billion. We do this by emboldening entrepreneurs or becoming one.">
    <link rel="canonical" href="https://aavishkaargroup.com/">
    <meta property="og:title" content="Aavishkaar Group: One of the largest Impact Platforms across the Global South">
  </head>
  <body>
    <header>
      <nav>
        <a href="https://aavishkaargroup.com/about/">About</a>
        <a href="https://aavishkaargroup.com/news-insights/">News &amp; Insights</a>
        <a href="https://aavishkaargroup.com/contact-us/">Contact us</a>
        <a href="https://aavishkaargroup.com/group-companies/aavishkaar-capital/">Aavishkaar Capital</a>
        <a href="https://aavishkaargroup.com/group-companies/aavishkaar-foundation/">Aavishkaar Foundation</a>
      </nav>
    </header>
    <main>
      <h1>We exist to bridge the opportunity gap for the emerging 3 billion</h1>
      <p>We do this by emboldening entrepreneurs or becoming one.</p>
      <section>
        <h2>Building impact investing ecosystems</h2>
        <p>140 Mn+ Underserved Customers (54% Women) supported through our Investments and Engagements</p>
      </section>
      <section>
        <h2>Latest News</h2>
        <article>
          <h3>Aavishkaar Group looks to balance long-cycle carbon</h3>
        </article>
      </section>
    </main>
    <footer>
      <a href="https://www.linkedin.com/company/aavishkaar-group">LinkedIn</a>
      <p>Disclaimer : It has come to our knowledge that certain individuals are fraudulently inducing people to invest funds in Aavishkaar Group with promises of high returns.</p>
    </footer>
  </body>
</html>
`

const contactHtml = `
<!doctype html>
<html lang="en">
  <head>
    <title>Contact Us - Aavishkaar Group</title>
    <meta name="description" content="Contact or send an email to Aavishkaar Group in case if you have any queries. Group of non-banking and financial companies in India.">
    <link rel="canonical" href="https://aavishkaargroup.com/contact-us/">
    <meta property="og:url" content="https://aavishkaargroup.com/contact-us/">
  </head>
  <body>
    <main>
      <h1>Contact Us</h1>
      <h2>Get in touch</h2>
      <p>Drop us an email at info@aavishkaargroup.com</p>
      <section>
        <h3>Mumbai</h3>
        <p>2nd Floor, Naman Center, C-31,G Block, Bandra Kurla Complex,Bandra East, Mumbai, Maharashtra 400051</p>
      </section>
      <section>
        <h3>Delhi</h3>
        <p>FS 05 &amp; FS 06, Collative Global Foyer, WhiteHouse NBCC Plaza, Pushp Vihar Saket, New Delhi, India</p>
      </section>
      <section>
        <h3>Nairobi</h3>
        <p>4th Floor, The Riverfront Prof. David Wasawo Drive Nairobi, Kenya</p>
      </section>
    </main>
    <footer>
      <a href="https://aavishkaargroup.com/about/">About</a>
      <a href="https://aavishkaargroup.com/contact-us/">Contact Us</a>
    </footer>
  </body>
</html>
`

const robotsTxt = `# START YOAST BLOCK
# ---------------------------
User-agent: *
Disallow:

Sitemap: https://aavishkaargroup.com/sitemap_index.xml
# ---------------------------
# END YOAST BLOCK`

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//aavishkaargroup.com/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://aavishkaargroup.com/page-sitemap.xml</loc>
    <lastmod>2026-04-09T07:08:02+00:00</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://aavishkaargroup.com/group-companies-sitemap.xml</loc>
    <lastmod>2026-06-11T07:10:30+00:00</lastmod>
  </sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Yoast SEO -->`

const missingRouteHtml = `
<!doctype html>
<html lang="en">
  <head>
    <title>Page not found | Aavishkaar</title>
  </head>
  <body>
    <header>
      <nav>
        <a href="https://aavishkaargroup.com/about/">About</a>
        <a href="https://aavishkaargroup.com/contact-us/">Contact us</a>
      </nav>
    </header>
    <main class="contact-banner wrapper-not-found">
      <h2>404</h2>
      <h3>Page not found !!!</h3>
      <h5>We're sorry, we couldn't find the page you requested... <a href="https://aavishkaargroup.com/">Go to Home</a></h5>
    </main>
    <footer>
      <p>We exist to bridge the opportunity gap for the emerging 3 billion.</p>
    </footer>
  </body>
</html>
`

const publicJobsHtml = `
<!doctype html>
<html lang="en">
  <head>
    <title>Careers - Aavishkaar Group</title>
  </head>
  <body>
    <main>
      <h1>Current Openings</h1>
      <article>
        <h2>Investment Associate</h2>
        <a href="https://aavishkaargroup.com/careers/investment-associate/">Apply now</a>
      </article>
    </main>
  </body>
</html>
`

test('Aavishkar sentinel pins the verified Aavishkaar Group first-party no-public-jobs surface', async () => {
  const aavishkar = await loadAavishkarModule()

  assert.equal(aavishkar.SOURCE, 'aavishkar')
  assert.equal(aavishkar.COMPANY, 'Aavishkar')
  assert.equal(aavishkar.OFFICIAL_BRAND_NAME, 'Aavishkaar Group')
  assert.equal(aavishkar.VERIFIED_ON, '2026-07-14')
  assert.equal(aavishkar.HOMEPAGE_URL, 'https://aavishkaargroup.com/')
  assert.equal(aavishkar.CONTACT_URL, 'https://aavishkaargroup.com/contact-us/')
  assert.equal(aavishkar.ROBOTS_TXT_URL, 'https://aavishkaargroup.com/robots.txt')
  assert.equal(aavishkar.SITEMAP_URL, 'https://aavishkaargroup.com/sitemap.xml')
  assert.deepEqual(aavishkar.CAREERS_ROUTE_URLS, [
    'https://aavishkaargroup.com/careers/',
    'https://aavishkaargroup.com/career/',
    'https://aavishkaargroup.com/jobs/',
    'https://aavishkaargroup.com/job/',
    'https://aavishkaargroup.com/join-us/',
    'https://aavishkaargroup.com/work-with-us/',
    'https://aavishkaargroup.com/openings/',
  ])

  assert.equal(aavishkar.hasOfficialHomepageSignal(homepageHtml), true)
  assert.equal(aavishkar.hasOfficialContactPageSignal(contactHtml), true)
  assert.equal(aavishkar.hasOpenRobotsSignal(robotsTxt), true)
  assert.equal(aavishkar.hasVerifiedSitemapIndex(sitemapXml), true)
  assert.equal(aavishkar.hasPublicJobsSignal(homepageHtml), false)
  assert.equal(aavishkar.hasFirstPartyCareerLikeLink(homepageHtml), false)
  assert.equal(aavishkar.hasPublicJobsSignal(publicJobsHtml), true)
  assert.equal(
    aavishkar.hasFirstPartyCareerLikeLink('<a href="https://aavishkaargroup.com/careers/">Careers</a>'),
    true,
  )
  assert.equal(
    aavishkar.isVerifiedMissingCareersRoute({
      status: 404,
      url: 'https://aavishkaargroup.com/careers/',
      html: missingRouteHtml,
    }),
    true,
  )
})

test('Aavishkar sentinel returns [] only while the verified Aavishkaar Group surface exposes no public jobs board', async () => {
  const aavishkar = await loadAavishkarModule()
  const requestedUrls = []

  const jobs = await aavishkar.createAavishkarScraper().run({
    fetchPage: async (url) => {
      requestedUrls.push(url)

      if (url === aavishkar.HOMEPAGE_URL) {
        return { status: 200, url, html: homepageHtml }
      }

      if (url === aavishkar.CONTACT_URL) {
        return { status: 200, url, html: contactHtml }
      }

      if (url === aavishkar.ROBOTS_TXT_URL) {
        return { status: 200, url, html: robotsTxt }
      }

      if (url === aavishkar.SITEMAP_URL) {
        return { status: 200, url: 'https://aavishkaargroup.com/sitemap_index.xml', html: sitemapXml }
      }

      if (aavishkar.CAREERS_ROUTE_URLS.includes(url)) {
        return { status: 404, url, html: missingRouteHtml }
      }

      throw new Error(`Unexpected URL: ${url}`)
    },
  })

  assert.deepEqual(requestedUrls, [
    aavishkar.HOMEPAGE_URL,
    aavishkar.CONTACT_URL,
    aavishkar.ROBOTS_TXT_URL,
    aavishkar.SITEMAP_URL,
    ...aavishkar.CAREERS_ROUTE_URLS,
  ])
  assert.deepEqual(jobs, [])
})

test('Aavishkar sentinel fails closed when the verified first-party surface drifts into a careers shell or public jobs page', async () => {
  const aavishkar = await loadAavishkarModule()

  await assert.rejects(
    aavishkar.createAavishkarScraper().run({
      fetchPage: async (url) => {
        if (url === aavishkar.HOMEPAGE_URL) {
          return {
            status: 200,
            url,
            html: `${homepageHtml}<a href="https://aavishkaargroup.com/careers/">Careers</a>`,
          }
        }

        throw new Error(`Unexpected URL: ${url}`)
      },
    }),
    /homepage now exposes a first-party careers or jobs link/i,
  )

  await assert.rejects(
    aavishkar.createAavishkarScraper().run({
      fetchPage: async (url) => {
        if (url === aavishkar.HOMEPAGE_URL) {
          return { status: 200, url, html: homepageHtml }
        }

        if (url === aavishkar.CONTACT_URL) {
          return { status: 200, url, html: contactHtml }
        }

        if (url === aavishkar.ROBOTS_TXT_URL) {
          return { status: 200, url, html: robotsTxt }
        }

        if (url === aavishkar.SITEMAP_URL) {
          return { status: 200, url: 'https://aavishkaargroup.com/sitemap_index.xml', html: sitemapXml }
        }

        if (url === aavishkar.CAREERS_ROUTE_URLS[0]) {
          return { status: 200, url, html: publicJobsHtml }
        }

        return { status: 404, url, html: missingRouteHtml }
      },
    }),
    /careers route changed materially or now exposes public jobs/i,
  )
})
