import assert from 'node:assert/strict'
import test from 'node:test'

import { generateCompanyCoverageReport } from '../providers/companyCoverage.js'
import { getScraperCatalog } from '../providers/index.js'

const sampleCsv = `row,company_name,url_in_text,note
1,"1,435 Companies Listed",,UI text
2,"Pune, maharashtra",,location fragment
3,24 7.ai,,
4,247.ai,,
5,Light & Wonder,,
6,Atlassian,,
7,ABB,,
8,Zensar Technologies,,
9,Siemens Digital Industries Software,,
10,Cadence Design Systems,,
11,Allstate,,
12,7-Eleven,,
13,Meta,,
14,VMware (Broadcom),,
15,Description,,
16,ACKO GENERAL INSURANCE,,
17,mthree,,
18,ASAPP,,
19,Botminds.ai,,
20,Goldi Solar Pvt. Ltd,,
21,Bosch Rexroth,,
22,Unknown Labs,,
23,Appview,,
24,Razor Pay,,
25,"iqigai.ai, built by Fractal Analytics",,
26,Logitech,,
27,A.P. Moller Maersk,,
28,ASSA ABLOY,,
29,Apollo Tyres,,
30,Altair,,
31,Ascendion,,
32,Allegis Global Solutions,,
33,Atkins,,
34,AtkinsRealis,,
35,AtkinsRéalis,,
36,Attentive.AI,,
37,Aspire Systems,,
38,AMAGI LABS,,
39,AlgoUniversity,,
40,Ammachi Labs,,
41,Applexus Technologies,,
42,AFFORDMED,,
43,Afford Medical Technologies Private Limited,,
44,Afford medical Technologies Pvt Ltd,,
45,Aizant Drug Research Solutions Pvt. Ltd.,,
46,Amrita,,
47,Amrita Edge,,
48,Amrita Institute of Medical Sciences,,
49,Amrita-BIOS,,
50,AutoRABIT',,
51,Axtria,,
52,AXIS BANK,,
53,Avantor,,
54,Altera,,
55,BNP Paribas,,
56,Barclays,,
57,BNY Mellon,,
58,Bank of New York Mellon,,
59,Bazaarvoice,,
60,Bahwan Cybertek,,
61,AurionPro,,
62,Bank of America,,
63,ViewzenLabs,,
64,Ashok Leyland,,
65,AVASOFT,,
66,Baxter India,,
67,Beroe Inc,,
68,Armstrong Fluid Technology,,
69,Bhanzu,,
70,AccioJob,,
71,AllGoVision,,
72,Avasarala Technologies,,
73,Acsia Technologies,,
74,Axelor,,
75,Aurigene,,
76,Aakash Byju's,,
77,Aakash Institute,,
78,Aujas Cybersecurity,,
79,Bloom Energy,,
80,Blubridge Technologies Pvt Ltd,,
81,Blue Binaries,,
82,Bluestock Fintech,,
83,BorgWarner,,
84,Bosch Global Software Technologies,,
85,Bounteous,,
86,Brillio,,
87,Broadridge,,
88,Broadridge Financial Solutions,,
89,Bull Machines,,
90,Burns & McDonnell,,
91,Byteridge,,
92,"CARIAD Inc, A Volkswagen Group Company",,
93,CBRE Group,,
94,CEAT,,
95,CELETTE India Pvt Ltd,,
96,CEI INDIA PRIVATE LIMITED,,
97,CG Power,,
98,Cyveritas Risk Advisory Pvt. Ltd,,
99,Engineerminds,,
100,INEL POWER SYSTEM ENGINEERS (P) LTD,,
101,IPR Technologies Pvt Ltd.,,
102,Prop Times,,
103,RV Systems Pvt Ltd,,
104,Rocket India (Mr. Cooper Group),,
105,SIPL,,
106,Tectonics Labs India Pvt. Ltd.,,
107,Valenta,,
108,3Edge Solutions,,
109,A&T Video Networks,,
110,ABInBev GCC India,,
111,ACS Network & Technologies,,
112,ACTA.ai,,
113,ADOR,,
114,AES Technologies,,
115,AETHRONE AEROSPACE,,
116,ALTEN India,,
117,AMAZECODES,,
118,AMI,,
119,ANAPTY CodeEmy Technologies PRIVATE LIMITED,,
120,ARTECH,,
121,Artech Infosystems,,
122,ARMS4AI,,
123,ARCI - Hyd,,
124,AVIN Systems,,
125,AXISCADES,,
126,ASACO PRIVATE LIMITED,,
127,COMVIVA,,
128,COHESITY,,
129,Canon India Pvt Ltd,,
130,Groww,,
131,Quantiphi,,
132,Marvell,,
133,Cimpress India,,
134,EasyEcom,,
135,Caterpillar,,
136,CaratLane,,
137,Publicis Sapient,,
138,Celigo,,
139,Cambridge Mobile Telematics,,
140,CM Telematics,,
141,o9 Solutions,,
142,Electronic Arts,,
143,Accolite Digital,,
144,Banyan Cloud,,
145,Cerner,,
146,Annalect,,
147,Annalect India,,
148,Centilytics,,
149,Bharat Forge,,
150,Beckman Coulter Diagnostics Company,,
151,Bajaj Finserv Health,,
152,Arcelor Mittal,,
153,CloudSEK,,
154,Cloudera,,
155,CloudThat,,
156,Clevertap,,
157,Chevron Global Technology and Services,,
158,Clix Capital,,
159,C-DAC,,
160,"C-DAC, Chennai",,
161,City Union Bank,,
162,CUB,,
163,CISAI - Amrita Vishwa Vidyapeetham,,
164,Cyware,,
165,Danaher Corporation,,
166,Danaher,,
167,DevRev,,
168,Auro.edu,,
169,CyberWarFare Labs (CWL),,
170,DATAMATICS,,
`

const singleColumnCsv = `24 7.ai,
3Edge Solutions,
Unknown Labs,
Description,description placeholder,
coimbatore,
`

const aliasCsv = `Engineersmind,
Wiley Edge,
GE Digital,
Worley India,
SanDisk,
Western Digital (SanDisk),
Sabre Hospitality Solutions,
Société Générale,
Nestle Company,
Cameron,
Schlumberger,
Fashnear,
Hitachi,
Survey Sparrow,
Vitesco Technologies,
Howden, a Chart Industries Company,
Zeon Charging,
Atria Convergence,
Atria Convergence Technologies,
`

const exactProviderCsv = `Havells,
Legrand,
Sabre Corporation,
SG Analytics,
Societe Generale,
Entrupy,
Zscaler,
ZoomRx,
Nestle,
Worldline India,
Warner Bros. Discovery,
Orange Business,
WatchGuard Technologies,
Temenos,
Tetra Pak,
Trianz,
Zifo,
Tiger Analytics,
Viasat,
Synechron,
Techolution,
Fev India,
SLB,
Tata Communications,
Neeyamo,
Matter EV,
Fox,
Alchemy Techsol India Pvt Ltd,
Fundsroom,
Digital Back Office Ltd,
Ganit Inc.,
Exposys Data Labs,
Airbound,
Everlife CPC,
Fanplay,
Optum,
G7 CR Technologies,
Network Intelligence,
Jumbotail,
JLL Technologies,
Impact Analytics,
Increff,
igus India,
MathWorks,
Mu Sigma,
National Payments Corporation Of India (NPCI),
Deduce Technologies,
Dremio,
Dr. Reddy's Laboratories,
Drip Capital,
Droom,
DSQ Software,
DTDC,
Dunnhumby,
Dunnhumby India,
dSpace India,
EazyDiner,
Edureka,
Dropbox,
Druva,
Dunzo,
EarlySalary,
eClerx,
ECM Data,
Ecom Express,
Edelweiss,
Ellenbarrie Industrial Gases,
Eicher,
Eka Software,
Eko,
Electronics Corporation of India Limited,
ElasticRun,
Eicher Motors,
Eicher Trucks,
eInfochips,
Eltropy,
Embibe,
Emerson India,
eMudhra,
Encompass,
Enfusion,
Enmovil,
ePayLater,
Epifi,
Eruditus,
ESDS,
ESL Steel,
Evalueserve,
Endurance,
Endurance Technologies,
Estee Lauder India,
Eternal,
Eton Solutions,
Eventus Security,
Everest,
Everest Industries,
Evolent Health,
Exa,
Exide Industries,
Expedia,
Experian India,
Expleo,
Fabel,
FabHotels,
Falabella,
Fampay,
FarEye,
Fastrack,
FCL,
Fedility Investments,
Fibe,
Figma,
FinBox,
Fincare,
Fincare Small Finance Bank,
Fino Payments Bank,
Finolex Cables,
Fireflies.ai,
FirstCry,
Five Star Business Finance,
Fivetran,
Flock,
Ford India,
Fanclash,
SocGen,
JPMorgan Chase,
Kapture CRM,
Five9 India,
Fleetx,
Fortis Healthcare,
Fraazo,
FreeCharge,
FreshMenu,
ReNew,
Samco,
FreshToHome,
Frontegg,
FrontRow,
Fullerton India,
FunPlus,
Fusion Microfinance,
Fyle,
GalaxEye,
Gameberry Labs,
Games24x7,
GamesKraft,
Garden Reach Shipbuilders,
Greenko,
Zeon Electric Private Limited,
`

test('generateCompanyCoverageReport filters noise rows and resolves aliases against the scraper catalog', () => {
  const report = generateCompanyCoverageReport({
    csvText: sampleCsv,
    catalog: getScraperCatalog(),
  })

  assert.equal(report.totalRows, 170)
  assert.equal(report.candidateRows, 167)
  assert.equal(report.matchedCount, 166)
  assert.equal(report.unmatchedCount, 1)

  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source]),
    [
      ['24 7.ai', '247ai'],
      ['247.ai', '247ai'],
      ['Light & Wonder', 'lnw'],
      ['Atlassian', 'atlassian'],
      ['ABB', 'abb'],
      ['Zensar Technologies', 'zensar'],
      ['Siemens Digital Industries Software', 'siemens'],
      ['Cadence Design Systems', 'cadence'],
      ['Allstate', 'allstate'],
      ['7-Eleven', 'seveneleven'],
      ['Meta', 'meta'],
      ['VMware (Broadcom)', 'broadcom'],
      ['ACKO GENERAL INSURANCE', 'acko'],
      ['mthree', 'mthree'],
      ['ASAPP', 'asapp'],
      ['Botminds.ai', 'botminds'],
      ['Goldi Solar Pvt. Ltd', 'goldisolar'],
      ['Bosch Rexroth', 'boschrexroth'],
      ['Appview', 'appviewx'],
      ['Razor Pay', 'razorpay'],
      ['iqigai.ai, built by Fractal Analytics', 'fractal'],
      ['Logitech', 'logitech'],
      ['A.P. Moller Maersk', 'maersk'],
      ['ASSA ABLOY', 'assaabloy'],
      ['Apollo Tyres', 'apollo'],
      ['Altair', 'siemens'],
      ['Ascendion', 'ascendion'],
      ['Allegis Global Solutions', 'allegis'],
      ['Atkins', 'atkinsrealis'],
      ['AtkinsRealis', 'atkinsrealis'],
      ['AtkinsRéalis', 'atkinsrealis'],
      ['Attentive.AI', 'attentiveai'],
      ['Aspire Systems', 'aspiresystems'],
      ['AMAGI LABS', 'amagi'],
      ['AlgoUniversity', 'algouniversity'],
      ['Ammachi Labs', 'ammachilabs'],
      ['Applexus Technologies', 'applexus'],
      ['AFFORDMED', 'affordmed'],
      ['Afford Medical Technologies Private Limited', 'affordmed'],
      ['Afford medical Technologies Pvt Ltd', 'affordmed'],
      ['Aizant Drug Research Solutions Pvt. Ltd.', 'aizant'],
      ['Amrita', 'amrita'],
      ['Amrita Edge', 'amrita'],
      ['Amrita Institute of Medical Sciences', 'amrita'],
      ['Amrita-BIOS', 'amrita'],
      ["AutoRABIT'", 'autorabit'],
      ['Axtria', 'axtria'],
      ['AXIS BANK', 'axisbank'],
      ['Avantor', 'avantor'],
      ['Altera', 'altera'],
      ['BNP Paribas', 'bnpparibas'],
      ['Barclays', 'barclays'],
      ['BNY Mellon', 'bnymellon'],
      ['Bank of New York Mellon', 'bnymellon'],
      ['Bazaarvoice', 'bazaarvoice'],
      ['Bahwan Cybertek', 'bahwancybertek'],
      ['AurionPro', 'aurionpro'],
      ['Bank of America', 'bankofamerica'],
      ['ViewzenLabs', 'viewzenlabs'],
      ['Ashok Leyland', 'ashokleyland'],
      ['AVASOFT', 'avasoft'],
      ['Baxter India', 'baxter'],
      ['Beroe Inc', 'beroe'],
      ['Armstrong Fluid Technology', 'armstrongfluidtechnology'],
      ['Bhanzu', 'bhanzu'],
      ['AccioJob', 'acciojob'],
      ['AllGoVision', 'allgovision'],
      ['Avasarala Technologies', 'avasarala'],
      ['Acsia Technologies', 'acsia'],
      ['Axelor', 'axelor'],
      ['Aurigene', 'aurigene'],
      ["Aakash Byju's", 'aakash'],
      ['Aakash Institute', 'aakash'],
      ['Aujas Cybersecurity', 'aujas'],
      ['Bloom Energy', 'bloomenergy'],
      ['Blubridge Technologies Pvt Ltd', 'blubridge'],
      ['Blue Binaries', 'bluebinaries'],
      ['Bluestock Fintech', 'bluestock'],
      ['BorgWarner', 'borgwarner'],
      ['Bosch Global Software Technologies', 'boschglobalsoftwaretechnologies'],
      ['Bounteous', 'bounteous'],
      ['Brillio', 'brillio'],
      ['Broadridge', 'broadridge'],
      ['Broadridge Financial Solutions', 'broadridge'],
      ['Bull Machines', 'bullmachines'],
      ['Burns & McDonnell', 'burnsmcdonnell'],
      ['Byteridge', 'byteridge'],
      ['CARIAD Inc, A Volkswagen Group Company', 'cariad'],
      ['CBRE Group', 'cbre'],
      ['CEAT', 'ceat'],
      ['CELETTE India Pvt Ltd', 'celette'],
      ['CEI INDIA PRIVATE LIMITED', 'cei'],
      ['CG Power', 'cgpower'],
      ['Cyveritas Risk Advisory Pvt. Ltd', 'cyveritas'],
      ['Engineerminds', 'engineerminds'],
      ['INEL POWER SYSTEM ENGINEERS (P) LTD', 'inel'],
      ['IPR Technologies Pvt Ltd.', 'iprtechnologies'],
      ['Prop Times', 'proptimes'],
      ['RV Systems Pvt Ltd', 'rvsystems'],
      ['Rocket India (Mr. Cooper Group)', 'rocketindia'],
      ['SIPL', 'sipl'],
      ['Tectonics Labs India Pvt. Ltd.', 'tectonicslabs'],
      ['Valenta', 'valenta'],
      ['3Edge Solutions', '3edge'],
      ['A&T Video Networks', 'atvideonetworks'],
      ['ABInBev GCC India', 'abinbevgccindia'],
      ['ACS Network & Technologies', 'acsnetworktechnologies'],
      ['ACTA.ai', 'actaai'],
      ['ADOR', 'ador'],
      ['AES Technologies', 'aestechnologies'],
      ['AETHRONE AEROSPACE', 'aethroneaerospace'],
      ['ALTEN India', 'altenindia'],
      ['AMAZECODES', 'amazecodes'],
      ['AMI', 'ami'],
      ['ANAPTY CodeEmy Technologies PRIVATE LIMITED', 'anaptycodeemy'],
      ['ARTECH', 'artechinfosystems'],
      ['Artech Infosystems', 'artechinfosystems'],
      ['ARMS4AI', 'arms4ai'],
      ['ARCI - Hyd', 'arcihyd'],
      ['AVIN Systems', 'avinsystems'],
      ['AXISCADES', 'axiscades'],
      ['ASACO PRIVATE LIMITED', 'asaco'],
      ['COMVIVA', 'comviva'],
      ['COHESITY', 'cohesity'],
      ['Canon India Pvt Ltd', 'canonindia'],
      ['Groww', 'groww'],
      ['Quantiphi', 'quantiphi'],
      ['Marvell', 'marvell'],
      ['Cimpress India', 'cimpress'],
      ['EasyEcom', 'easyecom'],
      ['Caterpillar', 'caterpillar'],
      ['CaratLane', 'caratlane'],
      ['Publicis Sapient', 'publicissapient'],
      ['Celigo', 'celigo'],
      ['Cambridge Mobile Telematics', 'cambridgemobiletelematics'],
      ['CM Telematics', 'cambridgemobiletelematics'],
      ['o9 Solutions', 'o9solutions'],
      ['Electronic Arts', 'electronicarts'],
      ['Accolite Digital', 'accolitedigital'],
      ['Banyan Cloud', 'banyancloud'],
      ['Cerner', 'cerner'],
      ['Annalect', 'annalect'],
      ['Annalect India', 'annalect'],
      ['Centilytics', 'centilytics'],
      ['Bharat Forge', 'bharatforge'],
      ['Beckman Coulter Diagnostics Company', 'beckmancoulterdiagnostics'],
      ['Bajaj Finserv Health', 'bajajfinservhealth'],
      ['Arcelor Mittal', 'arcelormittal'],
      ['CloudSEK', 'cloudsek'],
      ['Cloudera', 'cloudera'],
      ['CloudThat', 'cloudthat'],
      ['Clevertap', 'clevertap'],
      ['Chevron Global Technology and Services', 'chevronglobaltechnologyandservices'],
      ['Clix Capital', 'clixcapital'],
      ['C-DAC', 'cdac'],
      ['C-DAC, Chennai', 'cdac'],
      ['City Union Bank', 'cityunionbank'],
      ['CUB', 'cityunionbank'],
      ['CISAI - Amrita Vishwa Vidyapeetham', 'amrita'],
      ['Cyware', 'cyware'],
      ['Danaher Corporation', 'danahercorporation'],
      ['Danaher', 'danahercorporation'],
      ['DevRev', 'devrev'],
      ['Auro.edu', 'auro'],
      ['CyberWarFare Labs (CWL)', 'cyberwarfarelabs'],
      ['DATAMATICS', 'datamatics'],
    ],
  )

  assert.deepEqual(
    report.unmatched.map((item) => item.companyName),
    ['Unknown Labs'],
  )
})

test('generateCompanyCoverageReport supports the one-column company backlog csv format', () => {
  const report = generateCompanyCoverageReport({
    csvText: singleColumnCsv,
    catalog: getScraperCatalog(),
  })

  assert.equal(report.totalRows, 5)
  assert.equal(report.candidateRows, 3)
  assert.equal(report.matchedCount, 2)
  assert.equal(report.unmatchedCount, 1)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source]),
    [
      ['24 7.ai', '247ai'],
      ['3Edge Solutions', '3edge'],
    ],
  )
  assert.deepEqual(report.unmatched.map((item) => item.companyName), ['Unknown Labs'])
})

test('generateCompanyCoverageReport ignores a one-column company_name header row', () => {
  const report = generateCompanyCoverageReport({
    csvText: `company_name
Gati
`,
    catalog: [
      {
        source: 'gati',
        companyName: 'Gati',
        companyCareerPage: 'https://www.gati.com/',
      },
    ],
    aliasMap: {},
  })

  assert.equal(report.totalRows, 1)
  assert.equal(report.candidateRows, 1)
  assert.equal(report.matchedCount, 1)
  assert.equal(report.unmatchedCount, 0)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source]),
    [['Gati', 'gati']],
  )
})

test('generateCompanyCoverageReport resolves near-name aliases from the alias map', () => {
  const report = generateCompanyCoverageReport({
    csvText: aliasCsv,
    catalog: getScraperCatalog(),
  })

  assert.equal(report.totalRows, 19)
  assert.equal(report.candidateRows, 19)
  assert.equal(report.matchedCount, 19)
  assert.equal(report.unmatchedCount, 0)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source, item.provider?.source ?? null]),
    [
      ['Engineersmind', 'engineerminds', 'engineerminds'],
      ['Wiley Edge', 'mthree', 'mthree'],
      ['GE Digital', 'gevernova', 'gevernova'],
      ['Worley India', 'worley', 'worley'],
      ['SanDisk', 'sandisk', 'sandisk'],
      ['Western Digital (SanDisk)', 'sandisk', 'sandisk'],
      ['Sabre Hospitality Solutions', 'avenhospitality', 'avenhospitality'],
      ['Société Générale', 'societegenerale', 'societegenerale'],
      ['Nestle Company', 'nestle', 'nestle'],
      ['Cameron', 'slb', 'slb'],
      ['Schlumberger', 'slb', 'slb'],
      ['Fashnear', 'meesho', 'meesho'],
      ['Hitachi', 'hitachiindia', 'hitachiindia'],
      ['Survey Sparrow', 'surveysparrow', 'surveysparrow'],
      ['Vitesco Technologies', 'schaeffler', 'schaeffler'],
      ['Howden, a Chart Industries Company', 'chartindustries', 'chartindustries'],
      ['Zeon Charging', 'zeoncharging', 'zeoncharging'],
      ['Atria Convergence', 'actfibernet', 'actfibernet'],
      ['Atria Convergence Technologies', 'actfibernet', 'actfibernet'],
    ],
  )
})

test('generateCompanyCoverageReport resolves exact company names for newly added providers', () => {
  const report = generateCompanyCoverageReport({
    csvText: exactProviderCsv,
    catalog: getScraperCatalog(),
  })

  assert.equal(report.totalRows, 149)
  assert.equal(report.candidateRows, 149)
  assert.equal(report.matchedCount, 149)
  assert.equal(report.unmatchedCount, 0)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source, item.provider?.source ?? null]),
    [
      ['Havells', 'havells', 'havells'],
      ['Legrand', 'legrand', 'legrand'],
      ['Sabre Corporation', 'sabre', 'sabre'],
      ['SG Analytics', 'sganalytics', 'sganalytics'],
      ['Societe Generale', 'societegenerale', 'societegenerale'],
      ['Entrupy', 'entrupy', 'entrupy'],
      ['Zscaler', 'zscaler', 'zscaler'],
      ['ZoomRx', 'zoomrx', 'zoomrx'],
      ['Nestle', 'nestle', 'nestle'],
      ['Worldline India', 'worldlineindia', 'worldlineindia'],
      ['Warner Bros. Discovery', 'warnerbrosdiscovery', 'warnerbrosdiscovery'],
      ['Orange Business', 'orangebusiness', 'orangebusiness'],
      ['WatchGuard Technologies', 'watchguard', 'watchguard'],
      ['Temenos', 'temenos', 'temenos'],
      ['Tetra Pak', 'tetrapak', 'tetrapak'],
      ['Trianz', 'trianz', 'trianz'],
      ['Zifo', 'zifo', 'zifo'],
      ['Tiger Analytics', 'tigeranalytics', 'tigeranalytics'],
      ['Viasat', 'viasat', 'viasat'],
      ['Synechron', 'synechron', 'synechron'],
      ['Techolution', 'techolution', 'techolution'],
      ['Fev India', 'fevindia', 'fevindia'],
      ['SLB', 'slb', 'slb'],
      ['Tata Communications', 'tatacommunications', 'tatacommunications'],
      ['Neeyamo', 'neeyamo', 'neeyamo'],
      ['Matter EV', 'matterev', 'matterev'],
      ['Fox', 'fox', 'fox'],
      ['Alchemy Techsol India Pvt Ltd', 'alchemytechsolindia', 'alchemytechsolindia'],
      ['Fundsroom', 'fundsroom', 'fundsroom'],
      ['Digital Back Office Ltd', 'digitalbackoffice', 'digitalbackoffice'],
      ['Ganit Inc.', 'ganit', 'ganit'],
      ['Exposys Data Labs', 'exposysdatalabs', 'exposysdatalabs'],
      ['Airbound', 'airbound', 'airbound'],
      ['Everlife CPC', 'everlifecpc', 'everlifecpc'],
      ['Fanplay', 'fanplay', 'fanplay'],
      ['Optum', 'optum', 'optum'],
      ['G7 CR Technologies', 'g7cr', 'g7cr'],
      ['Network Intelligence', 'networkintelligence', 'networkintelligence'],
      ['Jumbotail', 'jumbotail', 'jumbotail'],
      ['JLL Technologies', 'jlltechnologies', 'jlltechnologies'],
      ['Impact Analytics', 'impactanalytics', 'impactanalytics'],
      ['Increff', 'increff', 'increff'],
      ['igus India', 'igusindia', 'igusindia'],
      ['MathWorks', 'mathworks', 'mathworks'],
      ['Mu Sigma', 'musigma', 'musigma'],
      ['National Payments Corporation Of India (NPCI)', 'npci', 'npci'],
      ['Deduce Technologies', 'deducetechnologies', 'deducetechnologies'],
      ['Dremio', 'dremio', 'dremio'],
      ['Dr. Reddy\'s Laboratories', 'drreddyslaboratories', 'drreddyslaboratories'],
      ['Drip Capital', 'dripcapital', 'dripcapital'],
      ['Droom', 'droom', 'droom'],
      ['DSQ Software', 'dsqsoftware', 'dsqsoftware'],
      ['DTDC', 'dtdc', 'dtdc'],
      ['Dunnhumby', 'dunnhumby', 'dunnhumby'],
      ['Dunnhumby India', 'dunnhumbyindia', 'dunnhumbyindia'],
      ['dSpace India', 'dspaceindia', 'dspaceindia'],
      ['EazyDiner', 'eazydiner', 'eazydiner'],
      ['Edureka', 'edureka', 'edureka'],
      ['Dropbox', 'dropbox', 'dropbox'],
      ['Druva', 'druva', 'druva'],
      ['Dunzo', 'dunzo', 'dunzo'],
      ['EarlySalary', 'earlysalary', 'earlysalary'],
      ['eClerx', 'eclerx', 'eclerx'],
      ['ECM Data', 'ecmdata', 'ecmdata'],
      ['Ecom Express', 'ecomexpress', 'ecomexpress'],
      ['Edelweiss', 'edelweiss', 'edelweiss'],
      ['Ellenbarrie Industrial Gases', 'ellenbarrieindustrialgases', 'ellenbarrieindustrialgases'],
      ['Eicher', 'eicher', 'eicher'],
      ['Eka Software', 'ekasoftware', 'ekasoftware'],
      ['Eko', 'eko', 'eko'],
      ['Electronics Corporation of India Limited', 'electronicscorporationofindialimited', 'electronicscorporationofindialimited'],
      ['ElasticRun', 'elasticrun', 'elasticrun'],
      ['Eicher Motors', 'eichermotors', 'eichermotors'],
      ['Eicher Trucks', 'eichertrucks', 'eichertrucks'],
      ['eInfochips', 'einfochips', 'einfochips'],
      ['Eltropy', 'eltropy', 'eltropy'],
      ['Embibe', 'embibe', 'embibe'],
      ['Emerson India', 'emersonindia', 'emersonindia'],
      ['eMudhra', 'emudhra', 'emudhra'],
      ['Encompass', 'encompass', 'encompass'],
      ['Enfusion', 'enfusion', 'enfusion'],
      ['Enmovil', 'enmovil', 'enmovil'],
      ['ePayLater', 'epaylater', 'epaylater'],
      ['Epifi', 'epifi', 'epifi'],
      ['Eruditus', 'eruditus', 'eruditus'],
      ['ESDS', 'esds', 'esds'],
      ['ESL Steel', 'eslsteel', 'eslsteel'],
      ['Evalueserve', 'evalueserve', 'evalueserve'],
      ['Endurance', 'endurance', 'endurance'],
      ['Endurance Technologies', 'endurancetechnologies', 'endurancetechnologies'],
      ['Estee Lauder India', 'esteelauderindia', 'esteelauderindia'],
      ['Eternal', 'eternal', 'eternal'],
      ['Eton Solutions', 'etonsolutions', 'etonsolutions'],
      ['Eventus Security', 'eventussecurity', 'eventussecurity'],
      ['Everest', 'everest', 'everest'],
      ['Everest Industries', 'everestindustries', 'everestindustries'],
      ['Evolent Health', 'evolenthealth', 'evolenthealth'],
      ['Exa', 'exa', 'exa'],
      ['Exide Industries', 'exideindustries', 'exideindustries'],
      ['Expedia', 'expedia', 'expedia'],
      ['Experian India', 'experianindia', 'experianindia'],
      ['Expleo', 'expleo', 'expleo'],
      ['Fabel', 'fabel', 'fabel'],
      ['FabHotels', 'fabhotels', 'fabhotels'],
      ['Falabella', 'falabella', 'falabella'],
      ['Fampay', 'fampay', 'fampay'],
      ['FarEye', 'fareye', 'fareye'],
      ['Fastrack', 'fastrack', 'fastrack'],
      ['FCL', 'fcl', 'fcl'],
      ['Fedility Investments', 'fedilityinvestments', 'fedilityinvestments'],
      ['Fibe', 'fibe', 'fibe'],
      ['Figma', 'figma', 'figma'],
      ['FinBox', 'finbox', 'finbox'],
      ['Fincare', 'fincare', 'fincare'],
      ['Fincare Small Finance Bank', 'fincaresmallfinancebank', 'fincaresmallfinancebank'],
      ['Fino Payments Bank', 'finopaymentsbank', 'finopaymentsbank'],
      ['Finolex Cables', 'finolexcables', 'finolexcables'],
      ['Fireflies.ai', 'firefliesai', 'firefliesai'],
      ['FirstCry', 'firstcry', 'firstcry'],
      ['Five Star Business Finance', 'fivestarbusinessfinance', 'fivestarbusinessfinance'],
      ['Fivetran', 'fivetran', 'fivetran'],
      ['Flock', 'flock', 'flock'],
      ['Ford India', 'fordindia', 'fordindia'],
      ['Fanclash', 'fanclash', 'fanclash'],
      ['SocGen', 'socgen', 'socgen'],
      ['JPMorgan Chase', 'jpmorganchase', 'jpmorganchase'],
      ['Kapture CRM', 'kapturecrm', 'kapturecrm'],
      ['Five9 India', 'five9india', 'five9india'],
      ['Fleetx', 'fleetx', 'fleetx'],
      ['Fortis Healthcare', 'fortishealthcare', 'fortishealthcare'],
      ['Fraazo', 'fraazo', 'fraazo'],
      ['FreeCharge', 'freecharge', 'freecharge'],
      ['FreshMenu', 'freshmenu', 'freshmenu'],
      ['ReNew', 'renew', 'renew'],
      ['Samco', 'samco', 'samco'],
      ['FreshToHome', 'freshtohome', 'freshtohome'],
      ['Frontegg', 'frontegg', 'frontegg'],
      ['FrontRow', 'frontrow', 'frontrow'],
      ['Fullerton India', 'fullertonindia', 'fullertonindia'],
      ['FunPlus', 'funplus', 'funplus'],
      ['Fusion Microfinance', 'fusionmicrofinance', 'fusionmicrofinance'],
      ['Fyle', 'fyle', 'fyle'],
      ['GalaxEye', 'galaxeye', 'galaxeye'],
      ['Gameberry Labs', 'gameberrylabs', 'gameberrylabs'],
      ['Games24x7', 'games24x7', 'games24x7'],
      ['GamesKraft', 'gameskraft', 'gameskraft'],
      ['Garden Reach Shipbuilders', 'gardenreachshipbuilders', 'gardenreachshipbuilders'],
      ['Greenko', 'greenko', 'greenko'],
      ['Zeon Electric Private Limited', 'zeoncharging', 'zeoncharging'],
    ],
  )
})

test('generateCompanyCoverageReport resolves Data Team backlog names to the Global Orizon provider', () => {
  const report = generateCompanyCoverageReport({
    csvText: `Data Team,
Our Data Team,
Global Orizon,
`,
    catalog: getScraperCatalog(),
  })

  assert.equal(report.totalRows, 3)
  assert.equal(report.candidateRows, 3)
  assert.equal(report.matchedCount, 3)
  assert.equal(report.unmatchedCount, 0)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source, item.provider?.source ?? null]),
    [
      ['Data Team', 'globalorizon', 'globalorizon'],
      ['Our Data Team', 'globalorizon', 'globalorizon'],
      ['Global Orizon', 'globalorizon', 'globalorizon'],
    ],
  )
})

test('generateCompanyCoverageReport prefers exact company names before fuzzy suffix-stripped matches', () => {
  const report = generateCompanyCoverageReport({
    csvText: `Anand Group,
Anand Group India,
`,
    catalog: [
      {
        source: 'anandgroup',
        companyName: 'Anand Group',
        companyCareerPage: 'https://careers.anandgroupindia.com/',
      },
      {
        source: 'anandgroupindia',
        companyName: 'Anand Group India',
        companyCareerPage: 'https://www.anandgroupindia.com/careers/',
      },
    ],
    aliasMap: {},
  })

  assert.equal(report.totalRows, 2)
  assert.equal(report.candidateRows, 2)
  assert.equal(report.matchedCount, 2)
  assert.equal(report.unmatchedCount, 0)
  assert.deepEqual(
    report.matched.map((item) => [item.companyName, item.source, item.provider?.source ?? null]),
    [
      ['Anand Group', 'anandgroup', 'anandgroup'],
      ['Anand Group India', 'anandgroupindia', 'anandgroupindia'],
    ],
  )
})
