import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import test from 'node:test'
import { run, HOMEPAGE_URL } from './script.js'
import { readInventoryEvidence } from '../../scraper-support/utils/inventoryEvidence.js'
const ALERTS_URL='https://jobs.jobvite.com/maven-wave-partners/jobAlerts'
const JOBS_URL='https://jobs.jobvite.com/maven-wave-partners/jobs'
const alerts=await fs.readFile(new URL('./fixtures/current-alerts.html',import.meta.url),'utf8')
const openings=await fs.readFile(new URL('./fixtures/current-openings.html',import.meta.url),'utf8')
const fixtureFetch=(alertHtml=alerts,jobHtml=openings,requested=[])=>async url=>{requested.push(url);if(url===HOMEPAGE_URL)return '<h1>Atos</h1><p>Accelerate intelligence</p>';if(url===ALERTS_URL)return alertHtml;if(url===JOBS_URL)return jobHtml;throw new Error('Unexpected URL '+url)}
test('verifies linked unfiltered Jobvite zero inventory without requesting broken legacy homepage',async()=>{const requested=[];const jobs=await run({fetchText:fixtureFetch(alerts,openings,requested)});assert.equal(jobs.length,0);assert.deepEqual(requested,[ALERTS_URL,JOBS_URL]);const e=readInventoryEvidence(jobs);assert.equal(e.status,'verified-empty');assert.equal(e.listingComplete,true);assert.equal(e.reportedTotal,0);assert.equal(e.indiaFacetCount,0);assert.equal(e.surface,JOBS_URL)})
test('job-alert signup alone is not an empty inventory',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,alerts)}),/Maven Wave.*inventory/i)})
test('wrong employer on current-openings page is rejected',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replaceAll('Maven Wave Partners','Other Company'))}),/Maven Wave.*identity/i)})
test('contradictory role links cannot accompany a verified-empty message',async()=>{const body=openings.replace('</article>','<a href="/maven-wave-partners/job/test123">Engineer</a></article>');await assert.rejects(run({fetchText:fixtureFetch(alerts,body)}),/Maven Wave.*inventory/i)})
test('missing empty message is not verified-empty',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('There are currently no open jobs.','Please check back'))}),/Maven Wave.*inventory/i)})
test('wrong published tenant binding is rejected',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace("companyEId: 'qWH9Vfwr'","companyEId: 'other'"))}),/Maven Wave.*identity/i)})
test('a foreign current-openings handoff is rejected before fetching it',async()=>{const requested=[];await assert.rejects(run({fetchText:fixtureFetch(alerts.replaceAll('/maven-wave-partners/jobs','https://example.com/maven-wave-partners/jobs'),openings,requested)}),/Maven Wave.*handoff/i);assert.deepEqual(requested,[ALERTS_URL])})

for(const stage of [ALERTS_URL,JOBS_URL])test('rejects a foreign final response for '+stage,async()=>{const requested=[];await assert.rejects(run({fetchText:fixtureFetch(),fetchImpl:async(url,options)=>{requested.push(url);assert.equal(options.redirect,'manual');return {url:url===stage?'https://example.com/foreign':url,status:200,ok:true,headers:new Headers(),text:async()=>url===ALERTS_URL?alerts:openings}}}),/Maven Wave.*response identity/i);assert.equal(requested.at(-1),stage)})
test('redirect response is rejected without following it',async()=>{const requested=[];await assert.rejects(run({fetchText:fixtureFetch(),fetchImpl:async(url,options)=>{requested.push(url);assert.equal(options.redirect,'manual');return {url,status:302,ok:false,headers:new Headers({location:'https://example.com/foreign'}),text:async()=>''}}}),/Maven Wave.*redirect/i);assert.deepEqual(requested,[ALERTS_URL])})

test('shared catalog resolves the actual Maven Wave module and current inventory metadata',async()=>{const {getScraperCatalog}=await import('../../scraper-support/providers/index.js');const {fileURLToPath,pathToFileURL}=await import('node:url');const p=getScraperCatalog().find(p=>p.source==='mavenwavepartners');assert.equal(p.modulePath,fileURLToPath(new URL('./script.js',import.meta.url)));assert.equal(p.companyCareerPage,JOBS_URL);const module=await import(pathToFileURL(p.modulePath).href);assert.equal(typeof module.run,'function');assert.equal(module.CAREERS_URL,JOBS_URL)})

test('visible native role links outside the first article contradict zero inventory',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('</article>','</article><a href="/maven-wave-partners/job/test123">Engineer</a>'))}),/Maven Wave.*inventory/i)})
test('commented empty paragraph is not live zero evidence',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('<p class="jv-text-center">\nThere are currently no open jobs.            </p>','<!-- <p class="jv-text-center">There are currently no open jobs.</p> -->'))}),/Maven Wave.*inventory/i)})
test('hidden empty paragraph is not live zero evidence',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('There are currently no open jobs.','There are currently no open jobs.').replace('<p class="jv-text-center">\nThere are currently','<p class="jv-text-center" hidden>\nThere are currently'))}),/Maven Wave.*inventory/i)})
test('commented expected tenant does not validate a different active tenant',async()=>{const body=openings.replace("companyEId: 'qWH9Vfwr'","/* companyEId: 'qWH9Vfwr', */ companyEId: 'other'");await assert.rejects(run({fetchText:fixtureFetch(alerts,body)}),/Maven Wave.*identity/i)})
test('duplicate active tenant fields are rejected',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace("companyEId: 'qWH9Vfwr'","companyEId: 'qWH9Vfwr', companyEId: 'other'"))}),/Maven Wave.*identity/i)})

test('an empty message inside a hidden inventory container is not evidence',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('<article class="jv-page-body"','<article hidden class="jv-page-body"'))}),/Maven Wave.*inventory/i)})
test('an empty message styled display-none is not evidence',async()=>{await assert.rejects(run({fetchText:fixtureFetch(alerts,openings.replace('<p class="jv-text-center">\nThere are currently','<p class="jv-text-center" style="display:none">\nThere are currently'))}),/Maven Wave.*inventory/i)})
