const scriptProvider = ({ source, companyName, companyDomain, companyCareerPage, modulePath, atsPlatform, paginationStrategy, extractionStrategy }) => ({
  source,
  companyName,
  adapter: 'script',
  modulePath,
  companyCareerPage,
  companyDomain,
  atsPlatform,
  countryFilter: 'India',
  paginationStrategy,
  extractionStrategy,
  parser: 'custom-script',
  normalizationProfile: 'engineering-default',
  dryRunFile: `${source}/jobs.json`,
  verifiedOn: '2026-07-23',
})

export const TARGETED_OPENING_PROVIDERS = [
  {
    source: 'yatra',
    companyName: 'Yatra',
    officialBrandName: 'Yatra',
    adapter: 'script',
    modulePath: '../../scraper/yatra/script.js',
    dryRunFile: 'yatra/jobs.json',
    companyCareerPage: 'https://www.yatra.com/career/job-portal',
    companyDomain: 'yatra.com',
    atsPlatform: 'yatra-first-party-career-portal',
    countryFilter: 'India',
    paginationStrategy: 'single-browser-rendered-job-portal',
    extractionStrategy: 'verified-first-party-job-portal+browser-rendered-listings+india-filter',
    parser: 'custom-script',
    normalizationProfile: 'engineering-default',
    verifiedOn: '2026-07-25',
    verifiedSurfaceSummary: 'Verified on Saturday, July 25, 2026 that https://www.yatra.com/career/home links to the enumerable first-party job portal at https://www.yatra.com/career/job-portal, which exposed current openings and jobs@yatra.com application instructions.',
  },
  scriptProvider({
    source: 'ptc', companyName: 'PTC', companyDomain: 'ptc.com',
    companyCareerPage: 'https://www.ptc.com/en/careers',
    modulePath: '../../scraper/ptc/script.js', atsPlatform: 'workday-jobs-api',
    paginationStrategy: 'dynamic-workday-india-locations-facet-plus-full-offset-pagination',
    extractionStrategy: 'official-workday-board+unfiltered-location-facet-discovery+india-filtered-jobs-api',
  }),
  scriptProvider({
    source: 'blackline', companyName: 'BlackLine', companyDomain: 'blackline.com',
    companyCareerPage: 'https://careers.blackline.com/careers-home/',
    modulePath: '../../scraper/blackline/script.js', atsPlatform: 'workday-jobs-api',
    paginationStrategy: 'dynamic-workday-india-locations-facet-plus-full-offset-pagination',
    extractionStrategy: 'verified-first-party-careers-redirect+official-workday-board+unfiltered-location-facet-discovery+india-filtered-jobs-api',
  }),
  scriptProvider({
    source: 'hubspot', companyName: 'HubSpot', companyDomain: 'hubspot.com',
    companyCareerPage: 'https://www.hubspot.com/careers/jobs',
    modulePath: '../../scraper/hubspot/script.js', atsPlatform: 'hubspot-first-party-graphql',
    paginationStrategy: 'complete-graphql-list',
    extractionStrategy: 'official-graphql-list+india-filter+detail-query',
  }),
  scriptProvider({
    source: 'docusign', companyName: 'DocuSign', companyDomain: 'docusign.com',
    companyCareerPage: 'https://careers.docusign.com/careers-home/jobs',
    modulePath: '../../scraper/docusign/script.js', atsPlatform: 'jibe-icims-api',
    paginationStrategy: 'page+total-count',
    extractionStrategy: 'official-jibe-jobs-api+india-filter',
  }),
  scriptProvider({
    source: 'sentinelone', companyName: 'SentinelOne', companyDomain: 'sentinelone.com',
    companyCareerPage: 'https://www.sentinelone.com/jobs/',
    modulePath: '../../scraper/sentinelone/script.js', atsPlatform: 'greenhouse',
    paginationStrategy: 'single-greenhouse-jobs-api-all-published',
    extractionStrategy: 'verified-first-party-jobs-page+sentinellabs-greenhouse-jobs-api+india-location-filter',
  }),
  scriptProvider({
    source: 'pega', companyName: 'Pegasystems', companyDomain: 'pega.com',
    companyCareerPage: 'https://www.pega.com/about/careers/job-listings',
    modulePath: '../../scraper/pega/script.js', atsPlatform: 'pega-drupal-careers',
    paginationStrategy: 'server-rendered-load-more-pages',
    extractionStrategy: 'official-listing-cards+india-filter+detail-pages',
  }),
  scriptProvider({
    source: 'qlik', companyName: 'Qlik', companyDomain: 'qlik.com',
    companyCareerPage: 'https://careerhub.qlik.com/careers?domain=qlik.com',
    modulePath: '../../scraper/qlik/script.js', atsPlatform: 'eightfold',
    paginationStrategy: 'validated-offset-limit-api',
    extractionStrategy: 'official-eightfold-listing-api+detail-api+india-filter+contract-validation',
  }),
  scriptProvider({
    source: 'godaddy', companyName: 'GoDaddy', companyDomain: 'godaddy.com',
    companyCareerPage: 'https://careers.godaddy/jobs/search',
    modulePath: '../../scraper/godaddy/script.js', atsPlatform: 'godaddy-first-party-careers',
    paginationStrategy: 'complete-server-rendered-search',
    extractionStrategy: 'official-search-cards+india-location-filter',
  }),
  scriptProvider({
    source: 'globant', companyName: 'Globant', companyDomain: 'globant.com',
    companyCareerPage: 'https://career.globant.com/',
    modulePath: '../../scraper/globant/script.js', atsPlatform: 'globant-sap-careers-api',
    paginationStrategy: 'page+show-more',
    extractionStrategy: 'official-sap-requisition-api+india-filter+legacy-target-transition',
  }),
  scriptProvider({
    source: 'zsassociates', companyName: 'ZS Associates', companyDomain: 'zs.com',
    companyCareerPage: 'https://jobs.zs.com/jobs?country=India',
    modulePath: '../../scraper/zsassociates/script.js', atsPlatform: 'jibe-icims-api',
    paginationStrategy: 'page+total-count',
    extractionStrategy: 'official-jibe-jobs-api+india-filter',
  }),
  scriptProvider({
    source: 'tenable', companyName: 'Tenable', companyDomain: 'tenable.com',
    companyCareerPage: 'https://www.tenable.com/careers',
    modulePath: '../../scraper/tenable/script.js', atsPlatform: 'greenhouse-board-api',
    paginationStrategy: 'single-greenhouse-board-feed',
    extractionStrategy: 'verified-first-party-careers-handoff+official-greenhouse-board-api+india-location-and-country-metadata-filter',
  }),
  scriptProvider({
    source: 'renesas', companyName: 'Renesas Electronics', companyDomain: 'renesas.com',
    companyCareerPage: 'https://jobs.renesas.com/india',
    modulePath: '../../scraper/renesas/script.js', atsPlatform: 'attrax-server-rendered-careers',
    paginationStrategy: 'india-filtered-page-count-pagination',
    extractionStrategy: 'official-india-careers-page+attrax-server-rendered-job-cards+india-filter',
  }),
]
