import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildScrapers,
  getScraperCatalog,
  hydrateProviderCatalogEntry,
} from '../providers/index.js'

test('getScraperCatalog merges workday and official portal providers into one registry', () => {
  const catalog = getScraperCatalog()

  const airbus = catalog.find((provider) => provider.source === 'airbus')
  const abb = catalog.find((provider) => provider.source === 'abb')
  const seveneleven = catalog.find((provider) => provider.source === 'seveneleven')
  const akamai = catalog.find((provider) => provider.source === 'akamai')
  const allstate = catalog.find((provider) => provider.source === 'allstate')
  const arm = catalog.find((provider) => provider.source === 'arm')
  const broadcom = catalog.find((provider) => provider.source === 'broadcom')
  const browserstack = catalog.find((provider) => provider.source === 'browserstack')
  const cisco = catalog.find((provider) => provider.source === 'cisco')
  const cadence = catalog.find((provider) => provider.source === 'cadence')
  const cognizant = catalog.find((provider) => provider.source === 'cognizant')
  const coforge = catalog.find((provider) => provider.source === 'coforge')
  const cyient = catalog.find((provider) => provider.source === 'cyient')
  const adobe = catalog.find((provider) => provider.source === 'adobe')
  const dell = catalog.find((provider) => provider.source === 'dell')
  const deloitte = catalog.find((provider) => provider.source === 'deloitte')
  const dxc = catalog.find((provider) => provider.source === 'dxc')
  const f5 = catalog.find((provider) => provider.source === 'f5')
  const hpinc = catalog.find((provider) => provider.source === 'hpinc')
  const hpe = catalog.find((provider) => provider.source === 'hpe')
  const inmobi = catalog.find((provider) => provider.source === 'inmobi')
  const intel = catalog.find((provider) => provider.source === 'intel')
  const intuit = catalog.find((provider) => provider.source === 'intuit')
  const kpmg = catalog.find((provider) => provider.source === 'kpmg')
  const ltimindtree = catalog.find((provider) => provider.source === 'ltimindtree')
  const lenovo = catalog.find((provider) => provider.source === 'lenovo')
  const logitech = catalog.find((provider) => provider.source === 'logitech')
  const mastercard = catalog.find((provider) => provider.source === 'mastercard')
  const meta = catalog.find((provider) => provider.source === 'meta')
  const motorolasolutions = catalog.find((provider) => provider.source === 'motorolasolutions')
  const nvidia = catalog.find((provider) => provider.source === 'nvidia')
  const netapp = catalog.find((provider) => provider.source === 'netapp')
  const ola = catalog.find((provider) => provider.source === 'ola')
  const olaelectric = catalog.find((provider) => provider.source === 'olaelectric')
  const opentext = catalog.find((provider) => provider.source === 'opentext')
  const oracle = catalog.find((provider) => provider.source === 'oracle')
  const paloalto = catalog.find((provider) => provider.source === 'paloalto')
  const sap = catalog.find((provider) => provider.source === 'sap')
  const google = catalog.find((provider) => provider.source === 'google')
  const cgi = catalog.find((provider) => provider.source === 'cgi')
  const hcltech = catalog.find((provider) => provider.source === 'hcltech')
  const mphasis = catalog.find((provider) => provider.source === 'mphasis')
  const nokia = catalog.find((provider) => provider.source === 'nokia')
  const questglobal = catalog.find((provider) => provider.source === 'questglobal')
  const persistent = catalog.find((provider) => provider.source === 'persistent')
  const redhat = catalog.find((provider) => provider.source === 'redhat')
  const salesforce = catalog.find((provider) => provider.source === 'salesforce')
  const samsungresearch = catalog.find((provider) => provider.source === 'samsungresearch')
  const sharechat = catalog.find((provider) => provider.source === 'sharechat')
  const siemens = catalog.find((provider) => provider.source === 'siemens')
  const sony = catalog.find((provider) => provider.source === 'sony')
  const snowflake = catalog.find((provider) => provider.source === 'snowflake')
  const synopsys = catalog.find((provider) => provider.source === 'synopsys')
  const tcs = catalog.find((provider) => provider.source === 'tcs')
  const tataelxsi = catalog.find((provider) => provider.source === 'tataelxsi')
  const tatamotors = catalog.find((provider) => provider.source === 'tatamotors')
  const tatatechnologies = catalog.find((provider) => provider.source === 'tatatechnologies')
  const techmahindra = catalog.find((provider) => provider.source === 'techmahindra')
  const zensar = catalog.find((provider) => provider.source === 'zensar')
  const zoom = catalog.find((provider) => provider.source === 'zoom')
  const workday = catalog.find((provider) => provider.source === 'workday')
  const wipro = catalog.find((provider) => provider.source === 'wipro')
  const autodesk = catalog.find((provider) => provider.source === 'autodesk')
  const rubrik = catalog.find((provider) => provider.source === 'rubrik')

  assert.ok(airbus)
  assert.equal(airbus.adapter, 'workday')
  assert.equal(airbus.atsPlatform, 'workday')
  assert.equal(airbus.companyCareerPage, airbus.baseUrl)
  assert.match(airbus.companyDomain, /wd\d+\.myworkdayjobs\.com$/)

  assert.ok(abb)
  assert.equal(abb.adapter, 'script')
  assert.equal(abb.atsPlatform, 'phenom')
  assert.match(abb.companyCareerPage, /careers\.abb\/global\/en\/search-results/i)
  assert.equal(abb.companyDomain, 'careers.abb')
  assert.match(abb.baseUrl, /abb\.wd3\.myworkdayjobs\.com\/External_Career_Page/i)

  assert.ok(allstate)
  assert.equal(allstate.adapter, 'script')
  assert.equal(allstate.atsPlatform, 'official-company-careers-json-api')
  assert.match(allstate.companyCareerPage, /allstate\.jobs\/job-search-results/i)
  assert.equal(allstate.companyDomain, 'allstate.jobs')
  assert.match(allstate.baseUrl, /allstate\.wd5\.myworkdayjobs\.com\/allstate_careers/i)

  assert.ok(seveneleven)
  assert.equal(seveneleven.adapter, 'script')
  assert.equal(seveneleven.atsPlatform, 'official-company-careers')
  assert.match(seveneleven.companyCareerPage, /careers\.7-eleven\.com\/search-jobs\?l=India/i)
  assert.equal(seveneleven.companyDomain, 'careers.7-eleven.com')

  assert.ok(akamai)
  assert.equal(akamai.adapter, 'script')
  assert.equal(akamai.atsPlatform, 'oracle-cloud')
  assert.match(akamai.companyCareerPage, /akamai\.com\/careers/i)
  assert.equal(akamai.companyDomain, 'akamai.com')

  assert.ok(arm)
  assert.equal(arm.adapter, 'script')
  assert.equal(arm.atsPlatform, 'official-company-careers')
  assert.match(arm.companyCareerPage, /careers\.arm\.com/i)
  assert.equal(arm.companyDomain, 'careers.arm.com')

  assert.ok(adobe)
  assert.equal(adobe.adapter, 'script')
  assert.equal(adobe.atsPlatform, 'phenom')
  assert.match(adobe.companyCareerPage, /careers\.adobe\.com/i)
  assert.equal(adobe.companyDomain, 'careers.adobe.com')

  assert.ok(browserstack)
  assert.equal(browserstack.adapter, 'script')
  assert.equal(browserstack.atsPlatform, 'workday')
  assert.match(browserstack.companyCareerPage, /browserstack\.com\/careers/i)
  assert.equal(browserstack.companyDomain, 'browserstack.com')

  assert.ok(broadcom)
  assert.equal(broadcom.adapter, 'workday')
  assert.equal(broadcom.atsPlatform, 'workday')
  assert.match(broadcom.companyCareerPage, /broadcom\.com\/company\/careers/i)
  assert.equal(broadcom.companyDomain, 'broadcom.com')
  assert.match(broadcom.baseUrl, /broadcom\.wd1\.myworkdayjobs\.com\/External_Career/i)

  assert.ok(cisco)
  assert.equal(cisco.adapter, 'script')
  assert.equal(cisco.atsPlatform, 'phenom')
  assert.match(cisco.companyCareerPage, /careers\.cisco\.com|jobs\.cisco\.com/i)
  assert.equal(cisco.companyDomain, 'careers.cisco.com')

  assert.ok(cadence)
  assert.equal(cadence.adapter, 'workday')
  assert.equal(cadence.atsPlatform, 'workday')
  assert.match(cadence.companyCareerPage, /cadence\.com\/.*careers\.html/i)
  assert.equal(cadence.companyDomain, 'cadence.com')
  assert.match(cadence.baseUrl, /cadence\.wd1\.myworkdayjobs\.com\/External_Careers/i)
  assert.equal(cadence.scraperTimeoutMs, 1200000)

  assert.ok(cognizant)
  assert.equal(cognizant.adapter, 'script')
  assert.equal(cognizant.atsPlatform, 'official-company-careers')
  assert.match(cognizant.companyCareerPage, /careers\.cognizant\.com\/india-en\/jobs/i)
  assert.equal(cognizant.companyDomain, 'careers.cognizant.com')

  assert.ok(coforge)
  assert.equal(coforge.adapter, 'script')
  assert.equal(coforge.atsPlatform, 'zwayam')
  assert.match(coforge.companyCareerPage, /careers\.coforge\.com\/coforge/i)
  assert.equal(coforge.companyDomain, 'careers.coforge.com')

  assert.ok(cyient)
  assert.equal(cyient.adapter, 'script')
  assert.equal(cyient.atsPlatform, 'zwayam')
  assert.match(cyient.companyCareerPage, /careers\.cyient\.com\/cyient/i)
  assert.equal(cyient.companyDomain, 'careers.cyient.com')

  assert.ok(dell)
  assert.equal(dell.adapter, 'script')
  assert.equal(dell.atsPlatform, 'oracle-cloud')
  assert.match(dell.companyCareerPage, /jobs\.dell\.com/i)
  assert.equal(dell.companyDomain, 'jobs.dell.com')

  assert.ok(deloitte)
  assert.equal(deloitte.adapter, 'script')
  assert.equal(deloitte.atsPlatform, 'avature')
  assert.match(deloitte.companyCareerPage, /usijobs\.deloitte\.com/i)
  assert.equal(deloitte.companyDomain, 'usijobs.deloitte.com')

  assert.ok(dxc)
  assert.equal(dxc.adapter, 'workday')
  assert.equal(dxc.atsPlatform, 'workday')
  assert.match(dxc.companyCareerPage, /careers\.dxc\.com/i)
  assert.equal(dxc.companyDomain, 'careers.dxc.com')
  assert.match(dxc.baseUrl, /dxctechnology\.wd1\.myworkdayjobs\.com\/DXCJobs/i)

  assert.ok(f5)
  assert.equal(f5.adapter, 'script')
  assert.equal(f5.atsPlatform, 'workday')
  assert.match(f5.companyCareerPage, /f5\.com\/company\/careers/i)
  assert.equal(f5.companyDomain, 'f5.com')
  assert.match(f5.baseUrl, /ffive\.wd5\.myworkdayjobs\.com\/f5jobs/i)

  assert.ok(hpe)
  assert.equal(hpe.adapter, 'script')
  assert.equal(hpe.atsPlatform, 'phenom')
  assert.match(hpe.companyCareerPage, /careers\.hpe\.com/i)
  assert.equal(hpe.companyDomain, 'careers.hpe.com')

  assert.ok(google)
  assert.equal(google.adapter, 'script')
  assert.equal(google.atsPlatform, 'official-company-careers')
  assert.match(google.companyCareerPage, /careers\.google\.com|google\.com\/about\/careers/i)

  assert.ok(cgi)
  assert.equal(cgi.adapter, 'script')
  assert.equal(cgi.atsPlatform, 'njoyn')
  assert.match(cgi.companyCareerPage, /cgi\.njoyn\.com/i)
  assert.equal(cgi.companyDomain, 'cgi.njoyn.com')

  assert.ok(hcltech)
  assert.equal(hcltech.adapter, 'script')
  assert.equal(hcltech.atsPlatform, 'successfactors')
  assert.match(hcltech.companyCareerPage, /careers\.hcltech\.com\/search/i)
  assert.equal(hcltech.companyDomain, 'careers.hcltech.com')

  assert.ok(hpinc)
  assert.equal(hpinc.adapter, 'workday')
  assert.equal(hpinc.atsPlatform, 'workday')
  assert.match(hpinc.companyCareerPage, /careers\.hp\.com/i)
  assert.equal(hpinc.companyDomain, 'careers.hp.com')
  assert.match(hpinc.baseUrl, /hp\.wd5\.myworkdayjobs\.com\/ExternalCareerSite/i)

  assert.ok(inmobi)
  assert.equal(inmobi.adapter, 'script')
  assert.equal(inmobi.atsPlatform, 'official-company-careers')
  assert.match(inmobi.companyCareerPage, /inmobi\.com\/company\/careers/i)
  assert.equal(inmobi.companyDomain, 'inmobi.com')

  assert.ok(intel)
  assert.equal(intel.adapter, 'workday')
  assert.equal(intel.atsPlatform, 'workday')
  assert.match(intel.companyCareerPage, /jobs\.intel\.com/i)
  assert.equal(intel.companyDomain, 'jobs.intel.com')
  assert.match(intel.baseUrl, /intel\.wd1\.myworkdayjobs\.com\/External/i)

  assert.ok(intuit)
  assert.equal(intuit.adapter, 'script')
  assert.equal(intuit.atsPlatform, 'avature')
  assert.match(intuit.companyCareerPage, /jobs\.intuit\.com\/location\/india-jobs\/27595\/1269750\/2/i)
  assert.equal(intuit.companyDomain, 'jobs.intuit.com')

  assert.ok(kpmg)
  assert.equal(kpmg.adapter, 'script')
  assert.equal(kpmg.atsPlatform, 'oracle-cloud')
  assert.match(kpmg.companyCareerPage, /kpmg\.com\/in\/en\/careers\.html/i)
  assert.equal(kpmg.companyDomain, 'kpmg.com')

  assert.ok(ltimindtree)
  assert.equal(ltimindtree.adapter, 'script')
  assert.equal(ltimindtree.atsPlatform, 'ripplehire')
  assert.equal(ltimindtree.companyCareerPage, 'https://www.ltm.com/careers')
  assert.equal(ltimindtree.companyDomain, 'ltm.com')

  assert.ok(lenovo)
  assert.equal(lenovo.adapter, 'script')
  assert.equal(lenovo.atsPlatform, 'avature')
  assert.match(lenovo.companyCareerPage, /jobs\.lenovo\.com\/en_US\/careers\/SearchJobs/i)
  assert.equal(lenovo.companyDomain, 'jobs.lenovo.com')

  assert.ok(logitech)
  assert.equal(logitech.adapter, 'workday')
  assert.equal(logitech.atsPlatform, 'workday')
  assert.match(logitech.companyCareerPage, /logitech\.com\/en-us\/careers/i)
  assert.equal(logitech.companyDomain, 'logitech.com')
  assert.match(logitech.baseUrl, /logitech\.wd5\.myworkdayjobs\.com\/Logitech/i)

  assert.ok(mastercard)
  assert.equal(mastercard.adapter, 'workday')
  assert.equal(mastercard.atsPlatform, 'workday')
  assert.match(mastercard.companyCareerPage, /careers\.mastercard\.com/i)
  assert.equal(mastercard.companyDomain, 'careers.mastercard.com')
  assert.match(mastercard.baseUrl, /mastercard\.wd1\.myworkdayjobs\.com\/CorporateCareers/i)
  assert.equal(mastercard.scraperTimeoutMs, 1200000)

  assert.ok(meta)
  assert.equal(meta.adapter, 'script')
  assert.equal(meta.atsPlatform, 'official-company-careers')
  assert.match(meta.companyCareerPage, /metacareers\.com\/jobsearch/i)
  assert.equal(meta.companyDomain, 'metacareers.com')

  assert.ok(motorolasolutions)
  assert.equal(motorolasolutions.adapter, 'workday')
  assert.equal(motorolasolutions.atsPlatform, 'workday')
  assert.match(motorolasolutions.companyCareerPage, /careers\.motorolasolutions\.com/i)
  assert.equal(motorolasolutions.companyDomain, 'careers.motorolasolutions.com')

  assert.ok(mphasis)
  assert.equal(mphasis.adapter, 'script')
  assert.equal(mphasis.atsPlatform, 'ripplehire')
  assert.match(mphasis.companyCareerPage, /careers\.mphasis\.com/i)
  assert.equal(mphasis.companyDomain, 'careers.mphasis.com')

  assert.ok(nokia)
  assert.equal(nokia.adapter, 'script')
  assert.equal(nokia.atsPlatform, 'oracle-cloud')
  assert.match(nokia.companyCareerPage, /jobs\.nokia\.com\/en\/sites\/CX_1/i)
  assert.equal(nokia.companyDomain, 'jobs.nokia.com')

  assert.ok(nvidia)
  assert.equal(nvidia.adapter, 'workday')
  assert.equal(nvidia.atsPlatform, 'workday')
  assert.match(nvidia.companyCareerPage, /nvidia\.com\/en-us\/about-nvidia\/careers/i)
  assert.equal(nvidia.companyDomain, 'nvidia.com')

  assert.ok(netapp)
  assert.equal(netapp.adapter, 'script')
  assert.equal(netapp.atsPlatform, 'official-company-careers')
  assert.match(netapp.companyCareerPage, /careers\.netapp\.com/i)
  assert.equal(netapp.companyDomain, 'careers.netapp.com')

  assert.ok(ola)
  assert.equal(ola.adapter, 'script')
  assert.equal(ola.atsPlatform, 'turbohire')
  assert.match(ola.companyCareerPage, /olacabs\.com\/careers/i)
  assert.equal(ola.companyDomain, 'olacabs.com')

  assert.ok(olaelectric)
  assert.equal(olaelectric.adapter, 'script')
  assert.equal(olaelectric.atsPlatform, 'turbohire')
  assert.match(olaelectric.companyCareerPage, /olaelectric\.com\/careers/i)
  assert.equal(olaelectric.companyDomain, 'olaelectric.com')

  assert.ok(opentext)
  assert.equal(opentext.adapter, 'script')
  assert.equal(opentext.atsPlatform, 'phenom')
  assert.match(opentext.companyCareerPage, /careers\.opentext\.com/i)
  assert.equal(opentext.companyDomain, 'careers.opentext.com')

  assert.ok(oracle)
  assert.equal(oracle.adapter, 'script')
  assert.equal(oracle.atsPlatform, 'oracle-cloud')
  assert.match(oracle.companyCareerPage, /careers\.oracle\.com\/en\/sites\/jobsearch\/jobs/i)
  assert.equal(oracle.companyDomain, 'careers.oracle.com')

  assert.ok(paloalto)
  assert.equal(paloalto.adapter, 'workday')
  assert.equal(paloalto.atsPlatform, 'workday')
  assert.match(paloalto.companyCareerPage, /jobs\.paloaltonetworks\.com\/en/i)
  assert.equal(paloalto.companyDomain, 'jobs.paloaltonetworks.com')
  assert.match(paloalto.baseUrl, /paloaltonetworks\.wd5\.myworkdayjobs\.com\/en-US\/panwexternalcareers/i)

  assert.ok(sap)
  assert.equal(sap.adapter, 'script')
  assert.equal(sap.atsPlatform, 'successfactors')
  assert.match(sap.companyCareerPage, /jobs\.sap\.com/i)
  assert.equal(sap.companyDomain, 'jobs.sap.com')

  assert.ok(questglobal)
  assert.equal(questglobal.adapter, 'script')
  assert.equal(questglobal.atsPlatform, 'phenom')
  assert.match(questglobal.companyCareerPage, /careers\.quest-global\.com/i)
  assert.equal(questglobal.companyDomain, 'careers.quest-global.com')

  assert.ok(persistent)
  assert.equal(persistent.adapter, 'script')
  assert.equal(persistent.atsPlatform, 'zwayam')
  assert.match(persistent.companyCareerPage, /careers\.persistent\.com\/explore-opportunities/i)
  assert.equal(persistent.companyDomain, 'careers.persistent.com')

  assert.ok(redhat)
  assert.equal(redhat.adapter, 'workday')
  assert.equal(redhat.atsPlatform, 'workday')
  assert.match(redhat.companyCareerPage, /redhat\.com\/jobs/i)
  assert.equal(redhat.companyDomain, 'redhat.com')
  assert.match(redhat.baseUrl, /redhat\.wd5\.myworkdayjobs\.com\/jobs\/?$/i)

  assert.ok(salesforce)
  assert.equal(salesforce.adapter, 'workday')
  assert.equal(salesforce.atsPlatform, 'workday')
  assert.match(salesforce.companyCareerPage, /careers\.salesforce\.com/i)
  assert.equal(salesforce.companyDomain, 'careers.salesforce.com')

  assert.ok(sharechat)
  assert.equal(sharechat.adapter, 'script')
  assert.equal(sharechat.atsPlatform, 'official-company-careers')
  assert.match(sharechat.companyCareerPage, /sharechat\.com\/careers/i)
  assert.equal(sharechat.companyDomain, 'sharechat.com')

  assert.ok(siemens)
  assert.equal(siemens.adapter, 'script')
  assert.equal(siemens.atsPlatform, 'avature')
  assert.match(siemens.companyCareerPage, /jobs\.siemens\.com/i)
  assert.equal(siemens.companyDomain, 'jobs.siemens.com')

  assert.ok(samsungresearch)
  assert.equal(samsungresearch.adapter, 'workday')
  assert.equal(samsungresearch.atsPlatform, 'workday')
  assert.match(samsungresearch.companyCareerPage, /research\.samsung\.com\/careers/i)
  assert.equal(samsungresearch.companyDomain, 'research.samsung.com')
  assert.match(samsungresearch.baseUrl, /sec\.wd3\.myworkdayjobs\.com\/en-US\/Samsung_Careers/i)

  assert.ok(sony)
  assert.equal(sony.adapter, 'workday')
  assert.equal(sony.atsPlatform, 'workday')
  assert.match(sony.companyCareerPage, /sonyglobal\.wd1\.myworkdayjobs\.com\/en-US\/SonyGlobalCareers/i)
  assert.equal(sony.companyDomain, 'sonyglobal.wd1.myworkdayjobs.com')
  assert.match(sony.baseUrl, /sonyglobal\.wd1\.myworkdayjobs\.com\/en-US\/SonyGlobalCareers/i)

  assert.ok(snowflake)
  assert.equal(snowflake.adapter, 'script')
  assert.equal(snowflake.atsPlatform, 'phenom')
  assert.match(snowflake.companyCareerPage, /careers\.snowflake\.com/i)
  assert.equal(snowflake.companyDomain, 'careers.snowflake.com')

  assert.ok(synopsys)
  assert.equal(synopsys.adapter, 'script')
  assert.equal(synopsys.atsPlatform, 'official-company-careers')
  assert.match(synopsys.companyCareerPage, /careers\.synopsys\.com/i)
  assert.equal(synopsys.companyDomain, 'careers.synopsys.com')

  assert.ok(tcs)
  assert.equal(tcs.adapter, 'script')
  assert.equal(tcs.atsPlatform, 'official-company-careers')
  assert.match(tcs.companyCareerPage, /ibegin\.tcsapps\.com\/candidate\/?$/i)
  assert.equal(tcs.companyDomain, 'ibegin.tcsapps.com')

  assert.ok(tataelxsi)
  assert.equal(tataelxsi.adapter, 'script')
  assert.equal(tataelxsi.atsPlatform, 'official-company-careers')
  assert.match(tataelxsi.companyCareerPage, /tataelxsi\.com\/careers\/job-openings/i)
  assert.equal(tataelxsi.companyDomain, 'tataelxsi.com')

  assert.ok(tatamotors)
  assert.equal(tatamotors.adapter, 'script')
  assert.equal(tatamotors.atsPlatform, 'successfactors')
  assert.match(tatamotors.companyCareerPage, /careers\.tatamotors\.com/i)
  assert.equal(tatamotors.companyDomain, 'careers.tatamotors.com')

  assert.ok(tatatechnologies)
  assert.equal(tatatechnologies.adapter, 'script')
  assert.equal(tatatechnologies.atsPlatform, 'ripplehire')
  assert.match(tatatechnologies.companyCareerPage, /tatatechnologies\.com\/in\/careers/i)
  assert.equal(tatatechnologies.companyDomain, 'tatatechnologies.com')

  assert.ok(techmahindra)
  assert.equal(techmahindra.adapter, 'script')
  assert.equal(techmahindra.atsPlatform, 'official-company-careers')
  assert.match(techmahindra.companyCareerPage, /careers\.techmahindra\.com/i)
  assert.equal(techmahindra.companyDomain, 'careers.techmahindra.com')

  assert.ok(zensar)
  assert.equal(zensar.adapter, 'script')
  assert.equal(zensar.atsPlatform, 'oracle-cloud')
  assert.match(zensar.companyCareerPage, /zensar\.com\/careers/i)
  assert.equal(zensar.companyDomain, 'zensar.com')

  assert.ok(zoom)
  assert.equal(zoom.adapter, 'script')
  assert.equal(zoom.atsPlatform, 'official-company-careers')
  assert.match(zoom.companyCareerPage, /careers\.zoom\.us\/jobs\/search/i)
  assert.equal(zoom.companyDomain, 'careers.zoom.us')

  assert.ok(workday)
  assert.equal(workday.adapter, 'workday')
  assert.equal(workday.atsPlatform, 'workday')
  assert.match(workday.companyCareerPage, /workday\.wd5\.myworkdayjobs\.com\/Workday/i)
  assert.equal(workday.companyDomain, 'workday.wd5.myworkdayjobs.com')

  assert.ok(wipro)
  assert.equal(wipro.adapter, 'script')
  assert.equal(wipro.atsPlatform, 'successfactors')
  assert.match(wipro.companyCareerPage, /careers\.wipro\.com\/search/i)
  assert.equal(wipro.companyDomain, 'careers.wipro.com')

  assert.ok(autodesk)
  assert.equal(autodesk.adapter, 'workday')
  assert.equal(autodesk.atsPlatform, 'workday')
  assert.match(autodesk.companyCareerPage, /autodesk\.wd1\.myworkdayjobs\.com\/EXT/i)
  assert.equal(autodesk.companyDomain, 'autodesk.wd1.myworkdayjobs.com')

  assert.ok(rubrik)
  assert.equal(rubrik.adapter, 'script')
  assert.equal(rubrik.atsPlatform, 'official-company-careers')
  assert.match(rubrik.companyCareerPage, /rubrik\.com/i)
})

test('buildScrapers keeps the existing runner contract while exposing provider metadata', () => {
  const scrapers = buildScrapers()
  const google = scrapers.find((scraper) => scraper.name === 'google')
  const akamai = scrapers.find((scraper) => scraper.name === 'akamai')
  const hcltech = scrapers.find((scraper) => scraper.name === 'hcltech')
  const inmobi = scrapers.find((scraper) => scraper.name === 'inmobi')
  const intel = scrapers.find((scraper) => scraper.name === 'intel')
  const intuit = scrapers.find((scraper) => scraper.name === 'intuit')
  const kpmg = scrapers.find((scraper) => scraper.name === 'kpmg')
  const ltimindtree = scrapers.find((scraper) => scraper.name === 'ltimindtree')
  const lenovo = scrapers.find((scraper) => scraper.name === 'lenovo')
  const logitech = scrapers.find((scraper) => scraper.name === 'logitech')
  const adobe = scrapers.find((scraper) => scraper.name === 'adobe')
  const abb = scrapers.find((scraper) => scraper.name === 'abb')
  const allstate = scrapers.find((scraper) => scraper.name === 'allstate')
  const seveneleven = scrapers.find((scraper) => scraper.name === 'seveneleven')
  const airbus = scrapers.find((scraper) => scraper.name === 'airbus')
  const arm = scrapers.find((scraper) => scraper.name === 'arm')
  const autodesk = scrapers.find((scraper) => scraper.name === 'autodesk')
  const broadcom = scrapers.find((scraper) => scraper.name === 'broadcom')
  const browserstack = scrapers.find((scraper) => scraper.name === 'browserstack')
  const cgi = scrapers.find((scraper) => scraper.name === 'cgi')
  const cisco = scrapers.find((scraper) => scraper.name === 'cisco')
  const cadence = scrapers.find((scraper) => scraper.name === 'cadence')
  const cognizant = scrapers.find((scraper) => scraper.name === 'cognizant')
  const coforge = scrapers.find((scraper) => scraper.name === 'coforge')
  const cyient = scrapers.find((scraper) => scraper.name === 'cyient')
  const dell = scrapers.find((scraper) => scraper.name === 'dell')
  const deloitte = scrapers.find((scraper) => scraper.name === 'deloitte')
  const dxc = scrapers.find((scraper) => scraper.name === 'dxc')
  const f5 = scrapers.find((scraper) => scraper.name === 'f5')
  const hpinc = scrapers.find((scraper) => scraper.name === 'hpinc')
  const hpe = scrapers.find((scraper) => scraper.name === 'hpe')
  const mastercard = scrapers.find((scraper) => scraper.name === 'mastercard')
  const meta = scrapers.find((scraper) => scraper.name === 'meta')
  const motorolasolutions = scrapers.find((scraper) => scraper.name === 'motorolasolutions')
  const mphasis = scrapers.find((scraper) => scraper.name === 'mphasis')
  const nokia = scrapers.find((scraper) => scraper.name === 'nokia')
  const nvidia = scrapers.find((scraper) => scraper.name === 'nvidia')
  const netapp = scrapers.find((scraper) => scraper.name === 'netapp')
  const ola = scrapers.find((scraper) => scraper.name === 'ola')
  const olaelectric = scrapers.find((scraper) => scraper.name === 'olaelectric')
  const opentext = scrapers.find((scraper) => scraper.name === 'opentext')
  const oracle = scrapers.find((scraper) => scraper.name === 'oracle')
  const paloalto = scrapers.find((scraper) => scraper.name === 'paloalto')
  const persistent = scrapers.find((scraper) => scraper.name === 'persistent')
  const sap = scrapers.find((scraper) => scraper.name === 'sap')
  const questglobal = scrapers.find((scraper) => scraper.name === 'questglobal')
  const redhat = scrapers.find((scraper) => scraper.name === 'redhat')
  const salesforce = scrapers.find((scraper) => scraper.name === 'salesforce')
  const samsungresearch = scrapers.find((scraper) => scraper.name === 'samsungresearch')
  const sharechat = scrapers.find((scraper) => scraper.name === 'sharechat')
  const siemens = scrapers.find((scraper) => scraper.name === 'siemens')
  const sony = scrapers.find((scraper) => scraper.name === 'sony')
  const snowflake = scrapers.find((scraper) => scraper.name === 'snowflake')
  const synopsys = scrapers.find((scraper) => scraper.name === 'synopsys')
  const tataelxsi = scrapers.find((scraper) => scraper.name === 'tataelxsi')
  const tatamotors = scrapers.find((scraper) => scraper.name === 'tatamotors')
  const tatatechnologies = scrapers.find((scraper) => scraper.name === 'tatatechnologies')
  const techmahindra = scrapers.find((scraper) => scraper.name === 'techmahindra')
  const zensar = scrapers.find((scraper) => scraper.name === 'zensar')
  const zoom = scrapers.find((scraper) => scraper.name === 'zoom')
  const workday = scrapers.find((scraper) => scraper.name === 'workday')
  const wipro = scrapers.find((scraper) => scraper.name === 'wipro')

  assert.ok(akamai)
  assert.equal(typeof akamai.run, 'function')
  assert.match(akamai.dryRunFile, /akamai[\\/]jobs\.json$/)
  assert.equal(akamai.provider.source, 'akamai')
  assert.equal(akamai.provider.atsPlatform, 'oracle-cloud')

  assert.ok(google)
  assert.equal(typeof google.run, 'function')
  assert.match(google.dryRunFile, /google[\\/]jobs\.json$/)
  assert.equal(google.provider.source, 'google')
  assert.equal(google.provider.atsPlatform, 'official-company-careers')

  assert.ok(hcltech)
  assert.equal(typeof hcltech.run, 'function')
  assert.match(hcltech.dryRunFile, /hcltech[\\/]jobs\.json$/)
  assert.equal(hcltech.provider.source, 'hcltech')
  assert.equal(hcltech.provider.atsPlatform, 'successfactors')

  assert.ok(hpinc)
  assert.equal(typeof hpinc.run, 'function')
  assert.match(hpinc.dryRunFile, /hpinc.workday[\\/]jobs\.json$/)
  assert.equal(hpinc.provider.source, 'hpinc')
  assert.equal(hpinc.provider.companyDomain, 'careers.hp.com')

  assert.ok(inmobi)
  assert.equal(typeof inmobi.run, 'function')
  assert.match(inmobi.dryRunFile, /inmobi[\\/]jobs\.json$/)
  assert.equal(inmobi.provider.source, 'inmobi')
  assert.equal(inmobi.provider.atsPlatform, 'official-company-careers')

  assert.ok(intel)
  assert.equal(typeof intel.run, 'function')
  assert.match(intel.dryRunFile, /intel.workday[\\/]jobs\.json$/)
  assert.equal(intel.provider.source, 'intel')
  assert.equal(intel.provider.companyDomain, 'jobs.intel.com')

  assert.ok(intuit)
  assert.equal(typeof intuit.run, 'function')
  assert.match(intuit.dryRunFile, /intuit[\\/]jobs\.json$/)
  assert.equal(intuit.provider.source, 'intuit')
  assert.equal(intuit.provider.atsPlatform, 'avature')
  assert.match(intuit.provider.companyCareerPage, /jobs\.intuit\.com\/location\/india-jobs\/27595\/1269750\/2/i)

  assert.ok(kpmg)
  assert.equal(typeof kpmg.run, 'function')
  assert.match(kpmg.dryRunFile, /kpmg[\\/]jobs\.json$/)
  assert.equal(kpmg.provider.source, 'kpmg')
  assert.equal(kpmg.provider.atsPlatform, 'oracle-cloud')

  assert.ok(ltimindtree)
  assert.equal(typeof ltimindtree.run, 'function')
  assert.match(ltimindtree.dryRunFile, /ltimindtree[\\/]jobs\.json$/)
  assert.equal(ltimindtree.provider.source, 'ltimindtree')
  assert.equal(ltimindtree.provider.atsPlatform, 'ripplehire')

  assert.ok(lenovo)
  assert.equal(typeof lenovo.run, 'function')
  assert.match(lenovo.dryRunFile, /lenovo[\\/]jobs\.json$/)
  assert.equal(lenovo.provider.source, 'lenovo')
  assert.equal(lenovo.provider.atsPlatform, 'avature')

  assert.ok(logitech)
  assert.equal(typeof logitech.run, 'function')
  assert.match(logitech.dryRunFile, /logitech.workday[\\/]jobs\.json$/)
  assert.equal(logitech.provider.source, 'logitech')
  assert.equal(logitech.provider.companyDomain, 'logitech.com')

  assert.ok(adobe)
  assert.equal(typeof adobe.run, 'function')
  assert.match(adobe.dryRunFile, /adobe[\\/]jobs\.json$/)
  assert.equal(adobe.provider.source, 'adobe')
  assert.equal(adobe.provider.atsPlatform, 'phenom')

  assert.ok(abb)
  assert.equal(typeof abb.run, 'function')
  assert.match(abb.dryRunFile, /abb.workday[\\/]jobs\.json$/)
  assert.equal(abb.provider.source, 'abb')
  assert.equal(abb.provider.atsPlatform, 'phenom')
  assert.equal(abb.provider.companyDomain, 'careers.abb')

  assert.ok(allstate)
  assert.equal(typeof allstate.run, 'function')
  assert.match(allstate.dryRunFile, /allstate.workday[\\/]jobs\.json$/)
  assert.equal(allstate.provider.source, 'allstate')
  assert.equal(allstate.provider.atsPlatform, 'official-company-careers-json-api')
  assert.equal(allstate.provider.companyDomain, 'allstate.jobs')

  assert.ok(seveneleven)
  assert.equal(typeof seveneleven.run, 'function')
  assert.match(seveneleven.dryRunFile, /seveneleven[\\/]jobs\.json$/)
  assert.equal(seveneleven.provider.source, 'seveneleven')
  assert.equal(seveneleven.provider.atsPlatform, 'official-company-careers')
  assert.equal(seveneleven.provider.companyDomain, 'careers.7-eleven.com')

  assert.ok(airbus)
  assert.equal(typeof airbus.run, 'function')
  assert.match(airbus.dryRunFile, /airbus.workday[\\/]jobs\.json$/)
  assert.equal(airbus.provider.source, 'airbus')
  assert.equal(airbus.provider.atsPlatform, 'workday')

  assert.ok(arm)
  assert.equal(typeof arm.run, 'function')
  assert.match(arm.dryRunFile, /arm[\\/]jobs\.json$/)
  assert.equal(arm.provider.source, 'arm')
  assert.equal(arm.provider.atsPlatform, 'official-company-careers')

  assert.ok(browserstack)
  assert.equal(typeof browserstack.run, 'function')
  assert.match(browserstack.dryRunFile, /browserstack.workday[\\/]jobs\.json$/)
  assert.equal(browserstack.provider.source, 'browserstack')
  assert.equal(browserstack.provider.companyDomain, 'browserstack.com')

  assert.ok(broadcom)
  assert.equal(typeof broadcom.run, 'function')
  assert.match(broadcom.dryRunFile, /broadcom.workday[\\/]jobs\.json$/)
  assert.equal(broadcom.provider.source, 'broadcom')
  assert.equal(broadcom.provider.companyDomain, 'broadcom.com')

  assert.ok(cgi)
  assert.equal(typeof cgi.run, 'function')
  assert.match(cgi.dryRunFile, /cgi[\\/]jobs\.json$/)
  assert.equal(cgi.provider.source, 'cgi')
  assert.equal(cgi.provider.atsPlatform, 'njoyn')

  assert.ok(cisco)
  assert.equal(typeof cisco.run, 'function')
  assert.match(cisco.dryRunFile, /cisco[\\/]jobs\.json$/)
  assert.equal(cisco.provider.source, 'cisco')
  assert.equal(cisco.provider.atsPlatform, 'phenom')

  assert.ok(cadence)
  assert.equal(typeof cadence.run, 'function')
  assert.match(cadence.dryRunFile, /cadence.workday[\\/]jobs\.json$/)
  assert.equal(cadence.provider.source, 'cadence')
  assert.equal(cadence.provider.companyDomain, 'cadence.com')
  assert.match(cadence.provider.baseUrl, /cadence\.wd1\.myworkdayjobs\.com\/External_Careers/i)
  assert.equal(cadence.provider.scraperTimeoutMs, 1200000)

  assert.ok(cognizant)
  assert.equal(typeof cognizant.run, 'function')
  assert.match(cognizant.dryRunFile, /cognizant[\\/]jobs\.json$/)
  assert.equal(cognizant.provider.source, 'cognizant')
  assert.equal(cognizant.provider.atsPlatform, 'official-company-careers')

  assert.ok(coforge)
  assert.equal(typeof coforge.run, 'function')
  assert.match(coforge.dryRunFile, /coforge[\\/]jobs\.json$/)
  assert.equal(coforge.provider.source, 'coforge')
  assert.equal(coforge.provider.atsPlatform, 'zwayam')

  assert.ok(cyient)
  assert.equal(typeof cyient.run, 'function')
  assert.match(cyient.dryRunFile, /cyient[\\/]jobs\.json$/)
  assert.equal(cyient.provider.source, 'cyient')
  assert.equal(cyient.provider.atsPlatform, 'zwayam')

  assert.ok(dell)
  assert.equal(typeof dell.run, 'function')
  assert.match(dell.dryRunFile, /dell[\\/]jobs\.json$/)
  assert.equal(dell.provider.source, 'dell')
  assert.equal(dell.provider.atsPlatform, 'oracle-cloud')

  assert.ok(deloitte)
  assert.equal(typeof deloitte.run, 'function')
  assert.match(deloitte.dryRunFile, /deloitte[\\/]jobs\.json$/)
  assert.equal(deloitte.provider.source, 'deloitte')
  assert.equal(deloitte.provider.atsPlatform, 'avature')

  assert.ok(dxc)
  assert.equal(typeof dxc.run, 'function')
  assert.match(dxc.dryRunFile, /dxc.workday[\\/]jobs\.json$/)
  assert.equal(dxc.provider.source, 'dxc')
  assert.equal(dxc.provider.companyDomain, 'careers.dxc.com')

  assert.ok(f5)
  assert.equal(typeof f5.run, 'function')
  assert.match(f5.dryRunFile, /f5.workday[\\/]jobs\.json$/)
  assert.equal(f5.provider.source, 'f5')
  assert.equal(f5.provider.companyDomain, 'f5.com')

  assert.ok(hpe)
  assert.equal(typeof hpe.run, 'function')
  assert.match(hpe.dryRunFile, /hpe[\\/]jobs\.json$/)
  assert.equal(hpe.provider.source, 'hpe')
  assert.equal(hpe.provider.atsPlatform, 'phenom')

  assert.ok(autodesk)
  assert.equal(typeof autodesk.run, 'function')
  assert.match(autodesk.dryRunFile, /autodesk.workday[\\/]jobs\.json$/)
  assert.equal(autodesk.provider.source, 'autodesk')
  assert.match(autodesk.provider.companyCareerPage, /autodesk\.wd1\.myworkdayjobs\.com\/EXT/i)

  assert.ok(mastercard)
  assert.equal(typeof mastercard.run, 'function')
  assert.match(mastercard.dryRunFile, /mastercard.workday[\\/]jobs\.json$/)
  assert.equal(mastercard.provider.source, 'mastercard')
  assert.match(mastercard.provider.baseUrl, /mastercard\.wd1\.myworkdayjobs\.com\/CorporateCareers/i)
  assert.equal(mastercard.provider.scraperTimeoutMs, 1200000)

  assert.ok(meta)
  assert.equal(typeof meta.run, 'function')
  assert.match(meta.dryRunFile, /meta[\\/]jobs\.json$/)
  assert.equal(meta.provider.source, 'meta')
  assert.equal(meta.provider.atsPlatform, 'official-company-careers')

  assert.ok(motorolasolutions)
  assert.equal(typeof motorolasolutions.run, 'function')
  assert.match(motorolasolutions.dryRunFile, /motorolasolutions.workday[\\/]jobs\.json$/)
  assert.equal(motorolasolutions.provider.source, 'motorolasolutions')
  assert.equal(motorolasolutions.provider.companyDomain, 'careers.motorolasolutions.com')

  assert.ok(mphasis)
  assert.equal(typeof mphasis.run, 'function')
  assert.match(mphasis.dryRunFile, /mphasis[\\/]jobs\.json$/)
  assert.equal(mphasis.provider.source, 'mphasis')
  assert.equal(mphasis.provider.atsPlatform, 'ripplehire')

  assert.ok(nokia)
  assert.equal(typeof nokia.run, 'function')
  assert.match(nokia.dryRunFile, /nokia[\\/]jobs\.json$/)
  assert.equal(nokia.provider.source, 'nokia')
  assert.equal(nokia.provider.atsPlatform, 'oracle-cloud')

  assert.ok(nvidia)
  assert.equal(typeof nvidia.run, 'function')
  assert.match(nvidia.dryRunFile, /nvidia.workday[\\/]jobs\.json$/)
  assert.equal(nvidia.provider.source, 'nvidia')
  assert.equal(nvidia.provider.companyDomain, 'nvidia.com')

  assert.ok(netapp)
  assert.equal(typeof netapp.run, 'function')
  assert.match(netapp.dryRunFile, /netapp[\\/]jobs\.json$/)
  assert.equal(netapp.provider.source, 'netapp')
  assert.equal(netapp.provider.atsPlatform, 'official-company-careers')

  assert.ok(ola)
  assert.equal(typeof ola.run, 'function')
  assert.match(ola.dryRunFile, /ola[\\/]jobs\.json$/)
  assert.equal(ola.provider.source, 'ola')
  assert.equal(ola.provider.atsPlatform, 'turbohire')

  assert.ok(olaelectric)
  assert.equal(typeof olaelectric.run, 'function')
  assert.match(olaelectric.dryRunFile, /olaelectric[\\/]jobs\.json$/)
  assert.equal(olaelectric.provider.source, 'olaelectric')
  assert.equal(olaelectric.provider.atsPlatform, 'turbohire')

  assert.ok(opentext)
  assert.equal(typeof opentext.run, 'function')
  assert.match(opentext.dryRunFile, /opentext[\\/]jobs\.json$/)
  assert.equal(opentext.provider.source, 'opentext')
  assert.equal(opentext.provider.atsPlatform, 'phenom')

  assert.ok(oracle)
  assert.equal(typeof oracle.run, 'function')
  assert.match(oracle.dryRunFile, /oracle[\\/]jobs\.json$/)
  assert.equal(oracle.provider.source, 'oracle')
  assert.equal(oracle.provider.atsPlatform, 'oracle-cloud')

  assert.ok(persistent)
  assert.equal(typeof persistent.run, 'function')
  assert.match(persistent.dryRunFile, /persistent[\\/]jobs\.json$/)
  assert.equal(persistent.provider.source, 'persistent')
  assert.equal(persistent.provider.atsPlatform, 'zwayam')

  assert.ok(paloalto)
  assert.equal(typeof paloalto.run, 'function')
  assert.match(paloalto.dryRunFile, /paloalto.workday[\\/]jobs\.json$/)
  assert.equal(paloalto.provider.source, 'paloalto')
  assert.equal(paloalto.provider.companyDomain, 'jobs.paloaltonetworks.com')

  assert.ok(sap)
  assert.equal(typeof sap.run, 'function')
  assert.match(sap.dryRunFile, /sap[\\/]jobs\.json$/)
  assert.equal(sap.provider.source, 'sap')
  assert.equal(sap.provider.atsPlatform, 'successfactors')

  assert.ok(questglobal)
  assert.equal(typeof questglobal.run, 'function')
  assert.match(questglobal.dryRunFile, /questglobal[\\/]jobs\.json$/)
  assert.equal(questglobal.provider.source, 'questglobal')
  assert.equal(questglobal.provider.atsPlatform, 'phenom')

  assert.ok(redhat)
  assert.equal(typeof redhat.run, 'function')
  assert.match(redhat.dryRunFile, /redhat.workday[\\/]jobs\.json$/)
  assert.equal(redhat.provider.source, 'redhat')
  assert.match(redhat.provider.baseUrl, /redhat\.wd5\.myworkdayjobs\.com\/jobs\/?$/i)

  assert.ok(salesforce)
  assert.equal(typeof salesforce.run, 'function')
  assert.match(salesforce.dryRunFile, /salesforce.workday[\\/]jobs\.json$/)
  assert.equal(salesforce.provider.source, 'salesforce')
  assert.equal(salesforce.provider.companyDomain, 'careers.salesforce.com')

  assert.ok(sharechat)
  assert.equal(typeof sharechat.run, 'function')
  assert.match(sharechat.dryRunFile, /sharechat[\\/]jobs\.json$/)
  assert.equal(sharechat.provider.source, 'sharechat')
  assert.equal(sharechat.provider.atsPlatform, 'official-company-careers')

  assert.ok(siemens)
  assert.equal(typeof siemens.run, 'function')
  assert.match(siemens.dryRunFile, /siemens[\\/]jobs\.json$/)
  assert.equal(siemens.provider.source, 'siemens')
  assert.equal(siemens.provider.atsPlatform, 'avature')

  assert.ok(samsungresearch)
  assert.equal(typeof samsungresearch.run, 'function')
  assert.match(samsungresearch.dryRunFile, /samsungresearch.workday[\\/]jobs\.json$/)
  assert.equal(samsungresearch.provider.source, 'samsungresearch')
  assert.equal(samsungresearch.provider.companyDomain, 'research.samsung.com')

  assert.ok(sony)
  assert.equal(typeof sony.run, 'function')
  assert.match(sony.dryRunFile, /sony.workday[\\/]jobs\.json$/)
  assert.equal(sony.provider.source, 'sony')
  assert.equal(sony.provider.companyDomain, 'sonyglobal.wd1.myworkdayjobs.com')

  assert.ok(snowflake)
  assert.equal(typeof snowflake.run, 'function')
  assert.match(snowflake.dryRunFile, /snowflake[\\/]jobs\.json$/)
  assert.equal(snowflake.provider.source, 'snowflake')
  assert.equal(snowflake.provider.atsPlatform, 'phenom')

  assert.ok(synopsys)
  assert.equal(typeof synopsys.run, 'function')
  assert.match(synopsys.dryRunFile, /synopsys[\\/]jobs\.json$/)
  assert.equal(synopsys.provider.source, 'synopsys')
  assert.equal(synopsys.provider.atsPlatform, 'official-company-careers')

  assert.ok(tataelxsi)
  assert.equal(typeof tataelxsi.run, 'function')
  assert.match(tataelxsi.dryRunFile, /tataelxsi[\\/]jobs\.json$/)
  assert.equal(tataelxsi.provider.source, 'tataelxsi')
  assert.equal(tataelxsi.provider.atsPlatform, 'official-company-careers')

  assert.ok(tatamotors)
  assert.equal(typeof tatamotors.run, 'function')
  assert.match(tatamotors.dryRunFile, /tatamotors[\\/]jobs\.json$/)
  assert.equal(tatamotors.provider.source, 'tatamotors')
  assert.equal(tatamotors.provider.atsPlatform, 'successfactors')

  assert.ok(tatatechnologies)
  assert.equal(typeof tatatechnologies.run, 'function')
  assert.match(tatatechnologies.dryRunFile, /tatatechnologies[\\/]jobs\.json$/)
  assert.equal(tatatechnologies.provider.source, 'tatatechnologies')
  assert.equal(tatatechnologies.provider.atsPlatform, 'ripplehire')

  assert.ok(techmahindra)
  assert.equal(typeof techmahindra.run, 'function')
  assert.match(techmahindra.dryRunFile, /techmahindra[\\/]jobs\.json$/)
  assert.equal(techmahindra.provider.source, 'techmahindra')
  assert.equal(techmahindra.provider.atsPlatform, 'official-company-careers')

  assert.ok(zensar)
  assert.equal(typeof zensar.run, 'function')
  assert.match(zensar.dryRunFile, /zensar[\\/]jobs\.json$/)
  assert.equal(zensar.provider.source, 'zensar')
  assert.equal(zensar.provider.atsPlatform, 'oracle-cloud')

  assert.ok(zoom)
  assert.equal(typeof zoom.run, 'function')
  assert.match(zoom.dryRunFile, /zoom[\\/]jobs\.json$/)
  assert.equal(zoom.provider.source, 'zoom')
  assert.equal(zoom.provider.atsPlatform, 'official-company-careers')

  assert.ok(workday)
  assert.equal(typeof workday.run, 'function')
  assert.match(workday.dryRunFile, /workday.workday[\\/]jobs\.json$/)
  assert.equal(workday.provider.source, 'workday')
  assert.equal(workday.provider.atsPlatform, 'workday')

  assert.ok(wipro)
  assert.equal(typeof wipro.run, 'function')
  assert.match(wipro.dryRunFile, /wipro[\\/]jobs\.json$/)
  assert.equal(wipro.provider.source, 'wipro')
  assert.equal(wipro.provider.atsPlatform, 'successfactors')
})

test('hydrateProviderCatalogEntry prefers the official company career page when deriving provider metadata', () => {
  const provider = hydrateProviderCatalogEntry({
    source: 'example-workday',
    company: 'Example Corp',
    adapter: 'workday',
    baseUrl: 'https://example.wd5.myworkdayjobs.com/en-US/External',
    companyCareerPage: 'https://careers.example.com',
  })

  assert.equal(provider.companyName, 'Example Corp')
  assert.equal(provider.companyCareerPage, 'https://careers.example.com')
  assert.equal(provider.companyDomain, 'careers.example.com')
  assert.equal(provider.atsPlatform, 'workday')
  assert.match(provider.dryRunFile, /example-workday\.workday[\\/]jobs\.json$/)
})

test('getScraperCatalog includes apiPortal providers with official metadata and config-driven dry-run files', () => {
  const catalog = getScraperCatalog()
  const amd = catalog.find((provider) => provider.source === 'amd')
  const cloudflare = catalog.find((provider) => provider.source === 'cloudflare')
  const cred = catalog.find((provider) => provider.source === 'cred')
  const databricks = catalog.find((provider) => provider.source === 'databricks')
  const razorpay = catalog.find((provider) => provider.source === 'razorpay')
  const freshworks = catalog.find((provider) => provider.source === 'freshworks')
  const github = catalog.find((provider) => provider.source === 'github')
  const gitlab = catalog.find((provider) => provider.source === 'gitlab')
  const meesho = catalog.find((provider) => provider.source === 'meesho')
  const phonepe = catalog.find((provider) => provider.source === 'phonepe')
  const postman = catalog.find((provider) => provider.source === 'postman')
  const stripe = catalog.find((provider) => provider.source === 'stripe')
  const swiggy = catalog.find((provider) => provider.source === 'swiggy')
  const twilio = catalog.find((provider) => provider.source === 'twilio')

  assert.ok(amd)
  assert.equal(amd.adapter, 'apiPortal')
  assert.equal(amd.atsPlatform, 'jibe')
  assert.match(amd.companyCareerPage, /careers\.amd\.com\/careers-home\/jobs/i)
  assert.equal(amd.companyDomain, 'careers.amd.com')
  assert.match(amd.config.discovery.listingApiUrl, /careers\.amd\.com\/api\/jobs/i)
  assert.match(amd.dryRunFile, /amd[\\/]jobs\.json$/)

  assert.ok(cloudflare)
  assert.equal(cloudflare.adapter, 'apiPortal')
  assert.equal(cloudflare.atsPlatform, 'greenhouse')
  assert.match(cloudflare.companyCareerPage, /cloudflare\.com\/careers/i)
  assert.equal(cloudflare.companyDomain, 'cloudflare.com')
  assert.match(cloudflare.config.discovery.listingApiUrl, /boards-api\.greenhouse\.io\/v1\/boards\/cloudflare\/jobs/i)

  assert.ok(cred)
  assert.equal(cred.adapter, 'apiPortal')
  assert.equal(cred.atsPlatform, 'lever')
  assert.match(cred.companyCareerPage, /careers\.cred\.club/i)
  assert.equal(cred.companyDomain, 'careers.cred.club')
  assert.match(cred.config.discovery.listingApiUrl, /api\.lever\.co\/v0\/postings\/cred/i)

  assert.ok(databricks)
  assert.equal(databricks.adapter, 'apiPortal')
  assert.equal(databricks.atsPlatform, 'greenhouse')
  assert.match(databricks.companyCareerPage, /databricks\.com\/company\/careers/i)
  assert.equal(databricks.companyDomain, 'databricks.com')
  assert.match(databricks.config.discovery.listingApiUrl, /boards-api\.greenhouse\.io\/v1\/boards\/databricks\/jobs/i)

  assert.ok(razorpay)
  assert.equal(razorpay.adapter, 'apiPortal')
  assert.equal(razorpay.atsPlatform, 'greenhouse')
  assert.match(razorpay.companyCareerPage, /razorpay\.com\/careers/i)
  assert.equal(razorpay.companyDomain, 'razorpay.com')
  assert.match(razorpay.dryRunFile, /razorpay[\\/]jobs\.json$/)

  assert.ok(freshworks)
  assert.equal(freshworks.adapter, 'apiPortal')
  assert.equal(freshworks.atsPlatform, 'smartrecruiters')
  assert.match(freshworks.companyCareerPage, /freshworks\.com\/company\/careers/i)
  assert.equal(freshworks.companyDomain, 'freshworks.com')

  assert.ok(github)
  assert.equal(github.adapter, 'apiPortal')
  assert.equal(github.atsPlatform, 'official-company-careers')
  assert.match(github.companyCareerPage, /github\.careers\/careers-home/i)
  assert.equal(github.companyDomain, 'github.careers')
  assert.match(github.config.discovery.listingApiUrl, /github\.careers\/api\/jobs/i)

  assert.ok(gitlab)
  assert.equal(gitlab.adapter, 'apiPortal')
  assert.equal(gitlab.atsPlatform, 'greenhouse')
  assert.match(gitlab.companyCareerPage, /about\.gitlab\.com\/jobs\/all-jobs/i)
  assert.equal(gitlab.companyDomain, 'about.gitlab.com')
  assert.match(gitlab.config.discovery.listingApiUrl, /boards-api\.greenhouse\.io\/v1\/boards\/gitlabcrm\/jobs/i)

  assert.ok(meesho)
  assert.equal(meesho.adapter, 'apiPortal')
  assert.equal(meesho.atsPlatform, 'lever')
  assert.match(meesho.companyCareerPage, /meesho\.io\/jobs/i)
  assert.equal(meesho.companyDomain, 'meesho.io')
  assert.match(meesho.config.discovery.listingApiUrl, /api\.lever\.co\/v0\/postings\/meesho/i)

  assert.ok(phonepe)
  assert.equal(phonepe.adapter, 'apiPortal')
  assert.equal(phonepe.atsPlatform, 'phonepe-first-party-json')
  assert.match(phonepe.companyCareerPage, /phonepe\.com\/careers\/job-openings/i)
  assert.equal(phonepe.companyDomain, 'phonepe.com')
  assert.match(phonepe.config.discovery.listingApiUrl, /phonepe\.com\/apollo\/job-postings\/latest\.json/i)

  assert.ok(postman)
  assert.equal(postman.adapter, 'apiPortal')
  assert.equal(postman.atsPlatform, 'workday')
  assert.match(postman.companyCareerPage, /postman\.com\/company\/careers/i)
  assert.equal(postman.companyDomain, 'postman.com')
  assert.match(postman.config.discovery.listingApiUrl, /postman\.com\/_mk-www-next\/api-cache\/careers-jobs\.json/i)

  assert.ok(stripe)
  assert.equal(stripe.adapter, 'apiPortal')
  assert.equal(stripe.atsPlatform, 'greenhouse')
  assert.match(stripe.companyCareerPage, /stripe\.com\/jobs/i)
  assert.equal(stripe.companyDomain, 'stripe.com')
  assert.match(stripe.config.discovery.listingApiUrl, /boards-api\.greenhouse\.io\/v1\/boards\/stripe\/jobs/i)

  assert.ok(swiggy)
  assert.equal(swiggy.adapter, 'apiPortal')
  assert.equal(swiggy.atsPlatform, 'mynexthire')
  assert.match(swiggy.companyCareerPage, /careers\.swiggy\.com/i)
  assert.equal(swiggy.companyDomain, 'careers.swiggy.com')

  assert.ok(twilio)
  assert.equal(twilio.adapter, 'apiPortal')
  assert.equal(twilio.atsPlatform, 'official-company-careers')
  assert.match(twilio.companyCareerPage, /jobs\.twilio\.com\/careers/i)
  assert.equal(twilio.companyDomain, 'jobs.twilio.com')
  assert.match(twilio.config.discovery.listingApiUrl, /jobs\.twilio\.com\/api\/pcsx\/search/i)
})

test('buildScrapers exposes a runnable apiPortal scraper without changing the runner contract', () => {
  const scrapers = buildScrapers()
  const amd = scrapers.find((scraper) => scraper.name === 'amd')
  const cloudflare = scrapers.find((scraper) => scraper.name === 'cloudflare')
  const cred = scrapers.find((scraper) => scraper.name === 'cred')
  const databricks = scrapers.find((scraper) => scraper.name === 'databricks')
  const razorpay = scrapers.find((scraper) => scraper.name === 'razorpay')
  const freshworks = scrapers.find((scraper) => scraper.name === 'freshworks')
  const github = scrapers.find((scraper) => scraper.name === 'github')
  const gitlab = scrapers.find((scraper) => scraper.name === 'gitlab')
  const meesho = scrapers.find((scraper) => scraper.name === 'meesho')
  const phonepe = scrapers.find((scraper) => scraper.name === 'phonepe')
  const postman = scrapers.find((scraper) => scraper.name === 'postman')
  const stripe = scrapers.find((scraper) => scraper.name === 'stripe')
  const swiggy = scrapers.find((scraper) => scraper.name === 'swiggy')
  const twilio = scrapers.find((scraper) => scraper.name === 'twilio')

  assert.ok(amd)
  assert.equal(typeof amd.run, 'function')
  assert.equal(amd.provider.adapter, 'apiPortal')
  assert.equal(amd.provider.parser, 'api-portal')
  assert.match(amd.provider.companyCareerPage, /careers\.amd\.com\/careers-home\/jobs/i)

  assert.ok(cloudflare)
  assert.equal(typeof cloudflare.run, 'function')
  assert.equal(cloudflare.provider.adapter, 'apiPortal')
  assert.equal(cloudflare.provider.parser, 'api-portal')
  assert.match(cloudflare.provider.companyCareerPage, /cloudflare\.com\/careers/i)

  assert.ok(cred)
  assert.equal(typeof cred.run, 'function')
  assert.equal(cred.provider.adapter, 'apiPortal')
  assert.equal(cred.provider.parser, 'api-portal')
  assert.match(cred.provider.companyCareerPage, /careers\.cred\.club/i)

  assert.ok(databricks)
  assert.equal(typeof databricks.run, 'function')
  assert.equal(databricks.provider.adapter, 'apiPortal')
  assert.equal(databricks.provider.parser, 'api-portal')
  assert.match(databricks.provider.companyCareerPage, /databricks\.com\/company\/careers/i)

  assert.ok(razorpay)
  assert.equal(typeof razorpay.run, 'function')
  assert.equal(razorpay.provider.adapter, 'apiPortal')
  assert.equal(razorpay.provider.parser, 'api-portal')

  assert.ok(freshworks)
  assert.equal(typeof freshworks.run, 'function')
  assert.equal(freshworks.provider.adapter, 'apiPortal')
  assert.equal(freshworks.provider.parser, 'api-portal')

  assert.ok(github)
  assert.equal(typeof github.run, 'function')
  assert.equal(github.provider.adapter, 'apiPortal')
  assert.equal(github.provider.parser, 'api-portal')
  assert.match(github.provider.companyCareerPage, /github\.careers\/careers-home/i)

  assert.ok(gitlab)
  assert.equal(typeof gitlab.run, 'function')
  assert.equal(gitlab.provider.adapter, 'apiPortal')
  assert.equal(gitlab.provider.parser, 'api-portal')
  assert.match(gitlab.provider.companyCareerPage, /about\.gitlab\.com\/jobs\/all-jobs/i)

  assert.ok(meesho)
  assert.equal(typeof meesho.run, 'function')
  assert.equal(meesho.provider.adapter, 'apiPortal')
  assert.equal(meesho.provider.parser, 'api-portal')
  assert.match(meesho.provider.companyCareerPage, /meesho\.io\/jobs/i)

  assert.ok(phonepe)
  assert.equal(typeof phonepe.run, 'function')
  assert.equal(phonepe.provider.adapter, 'apiPortal')
  assert.equal(phonepe.provider.parser, 'api-portal')

  assert.ok(postman)
  assert.equal(typeof postman.run, 'function')
  assert.equal(postman.provider.adapter, 'apiPortal')
  assert.equal(postman.provider.parser, 'api-portal')
  assert.match(postman.provider.companyCareerPage, /postman\.com\/company\/careers/i)

  assert.ok(stripe)
  assert.equal(typeof stripe.run, 'function')
  assert.equal(stripe.provider.adapter, 'apiPortal')
  assert.equal(stripe.provider.parser, 'api-portal')
  assert.match(stripe.provider.companyCareerPage, /stripe\.com\/jobs/i)

  assert.ok(swiggy)
  assert.equal(typeof swiggy.run, 'function')
  assert.equal(swiggy.provider.adapter, 'apiPortal')
  assert.equal(swiggy.provider.parser, 'api-portal')

  assert.ok(twilio)
  assert.equal(typeof twilio.run, 'function')
  assert.equal(twilio.provider.adapter, 'apiPortal')
  assert.equal(twilio.provider.parser, 'api-portal')
  assert.match(twilio.provider.companyCareerPage, /jobs\.twilio\.com\/careers/i)
})

test('getScraperCatalog includes recent Chevron, CleverTap, and CloudThat custom script providers', () => {
  const catalog = getScraperCatalog()
  const chevron = catalog.find((provider) => provider.source === 'chevronglobaltechnologyandservices')
  const cleverTap = catalog.find((provider) => provider.source === 'clevertap')
  const cloudthat = catalog.find((provider) => provider.source === 'cloudthat')

  assert.ok(chevron)
  assert.equal(chevron.adapter, 'script')
  assert.equal(chevron.atsPlatform, 'talentbrew-radancy')
  assert.match(chevron.companyCareerPage, /careers\.chevron\.com\/search-jobs/i)
  assert.equal(chevron.companyDomain, 'careers.chevron.com')
  assert.match(chevron.modulePath, /chevronglobaltechnologyandservices[\\/]script\.js$/i)

  assert.ok(cleverTap)
  assert.equal(cleverTap.adapter, 'script')
  assert.equal(cleverTap.atsPlatform, 'kula')
  assert.match(cleverTap.companyCareerPage, /clevertap\.com\/current-openings/i)
  assert.equal(cleverTap.companyDomain, 'clevertap.com')
  assert.match(cleverTap.modulePath, /clevertap[\\/]script\.js$/i)

  assert.ok(cloudthat)
  assert.equal(cloudthat.adapter, 'script')
  assert.equal(cloudthat.atsPlatform, 'keka-embed-api')
  assert.match(cloudthat.companyCareerPage, /cloudthat\.keka\.com\/careers/i)
  assert.equal(cloudthat.companyDomain, 'cloudthat.com')
  assert.match(cloudthat.modulePath, /cloudthat[\\/]script\.js$/i)
})

test('buildScrapers exposes runnable Chevron, CleverTap, and CloudThat scrapers', () => {
  const scrapers = buildScrapers()
  const chevron = scrapers.find((scraper) => scraper.name === 'chevronglobaltechnologyandservices')
  const cleverTap = scrapers.find((scraper) => scraper.name === 'clevertap')
  const cloudthat = scrapers.find((scraper) => scraper.name === 'cloudthat')

  assert.ok(chevron)
  assert.equal(typeof chevron.run, 'function')
  assert.match(chevron.dryRunFile, /chevronglobaltechnologyandservices[\\/]jobs\.json$/)
  assert.equal(chevron.provider.source, 'chevronglobaltechnologyandservices')
  assert.equal(chevron.provider.atsPlatform, 'talentbrew-radancy')

  assert.ok(cleverTap)
  assert.equal(typeof cleverTap.run, 'function')
  assert.match(cleverTap.dryRunFile, /clevertap[\\/]jobs\.json$/)
  assert.equal(cleverTap.provider.source, 'clevertap')
  assert.equal(cleverTap.provider.atsPlatform, 'kula')

  assert.ok(cloudthat)
  assert.equal(typeof cloudthat.run, 'function')
  assert.match(cloudthat.dryRunFile, /cloudthat[\\/]jobs\.json$/)
  assert.equal(cloudthat.provider.source, 'cloudthat')
  assert.equal(cloudthat.provider.atsPlatform, 'keka-embed-api')
})
