import test from 'node:test'
import assert from 'node:assert/strict'
import { runVerifiedEmployerLinkedIn } from '../shared/verifiedEmployerLinkedIn.js'
import { normalizeScrapedJob } from '../utils/normalizeScrapedJob.js'
import { generateFingerprint } from '../utils/saveToDB.js'

const C = { source:'verified-test', companyName:'Verified Co', officialUrl:'https://verified.example/', companyTenant:'verified-co', companyId:'123456', companyJobsUrl:'https://www.linkedin.com/company/verified-co/jobs/', listingPath:'/jobs/verified-co-jobs-worldwide', requestTimeoutMs:1000,
  nativeRoleEvidence:{ '1003':{title:'Remote Architect', location:'India', descriptionSignals:['Location: Bangalore / Remote']} } }
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;')
const roleUrl=id=>`https://in.linkedin.com/jobs/view/role-at-verified-co-${id}`
const boardUrl='https://www.linkedin.com/jobs/verified-co-jobs-worldwide?f_C=123456&trk=company'
const companyUrl='https://www.linkedin.com/company/verified-co'
const baseRows=()=>[{id:'1001',title:'Engineer',country:'IN',city:'Bengaluru',location:'Bengaluru, Karnataka, India'},{id:'1002',title:'Engineer',country:'US',city:'Indianapolis',location:'Indianapolis, Indiana, United States'},{id:'1003',title:'Remote Architect',country:'IN',city:null,location:'India',native:true}].map(r=>({...r,description:`<p>${r.title}</p><div><h2>Responsibilities</h2><p>Build reliable services with our team. ${r.native?'Location: Bangalore / Remote':'Work on complex production systems.'}</p></div><p>Required experience: 3+ years.</p>`}))
function build(){const rows=baseRows(),pages=new Map();const refresh=()=>{
 pages.set(C.officialUrl,{url:C.officialUrl,body:`<title>Verified Co</title><a href="${C.companyJobsUrl}">Careers</a>`});pages.set(C.companyJobsUrl,{url:companyUrl,body:`<h1>Verified Co</h1><a href="${esc(boardUrl)}">See jobs</a>`});
 pages.set(boardUrl,{url:boardUrl,body:`<span class="results-context-header__job-count">${rows.length}</span><span class="results-context-header__query-search">Verified Co Jobs in Worldwide</span><ul class="jobs-search__results-list">${rows.map(r=>`<li><div class="base-card
 job-search-card" data-entity-urn="urn:li:jobPosting:${r.id}"><a class="base-card__full-link" href="${roleUrl(r.id)}"></a><h3 class="base-search-card__title">${r.title}</h3><a class="hidden-nested-link" href="${companyUrl}">Verified Co</a><span class="job-search-card__location">${r.location}</span></div></li>`).join('')}</ul><p>You've viewed all jobs for this search</p>`});
 for(const r of rows){const schema={'@context':'https://schema.org','@type':'JobPosting',title:r.title,description:r.description,hiringOrganization:{'@type':'Organization',name:'Verified Co',sameAs:companyUrl},jobLocation:{'@type':'Place',address:{'@type':'PostalAddress',addressCountry:r.country,addressLocality:r.city,addressRegion:null}},datePosted:'2026-09-01',validThrough:'2026-10-01',employmentType:'FULL_TIME'};const url=roleUrl(r.id),auth=`https://www.linkedin.com/signup/cold-join?session_redirect=${encodeURIComponent(url)}`;
 pages.set(url,{url,body:`<link rel="canonical" href="${url}"><h1 class="top-card-layout__title">${r.title}</h1><a class="topcard__org-name-link" href="${companyUrl}">Verified Co</a><span class="topcard__flavor topcard__flavor--bullet">${r.location}</span><span class="num-applicants__caption topcard__flavor--metadata topcard__flavor--bullet">56 applicants</span><div class="show-more-less-html__markup">${r.description}</div>${r.native?`<button id="topbar-apply" data-tracking-control-name="public_jobs_apply-link-onsite">Apply</button><a data-tracking-control-name="public_jobs_nav-header-signin" href="${auth}">Sign in</a>`:`<button id="topbar-apply" data-modal="apply-modal">Apply</button><div id="apply-modal"><a data-tracking-control-name="public_jobs_apply-link-offsite_contextual-sign-in-modal_join-link" href="${auth}">Join now</a></div><script type="application/ld+json">${JSON.stringify(schema)}</script>`}`});}
};refresh();return{rows,pages,refresh}}
const fake=(pages,calls=[])=>async(url,options)=>{calls.push(url);assert(options.signal);const p=pages.get(url);assert(p,url);return {ok:true,status:200,url:p.url,text:async()=>p.body}}
const run=(b,extra={})=>runVerifiedEmployerLinkedIn(C,{fetchImpl:fake(b.pages),now:()=> '2026-09-13T00:00:00.000Z',...extra})

test('complete employer board validates foreign and native details before India/cap, with stable distinct identity',async()=>{const b=build(),calls=[];const all=await run(b,{fetchImpl:fake(b.pages,calls),maxJobs:0});assert.equal(calls.length,6);assert.equal(all.length,2);assert(all.every(x=>x.applicationRequiresAccount===true&&x.sourceListingComplete&&x.publicExperienceChecked));assert.equal(all[0].employmentType,'Full-time');assert(all[0].jobDescription.includes('Build reliable services'));assert(all[0].jobDescription.includes('Required experience'));assert.equal(all[1].city,null);assert.equal(all[1].remoteStatus,'Remote');assert.equal(new Set(all.map(generateFingerprint)).size,2);assert.deepEqual(all.map(generateFingerprint),all.map(x=>generateFingerprint(normalizeScrapedJob(x))));const limited=[];assert.equal((await run(b,{fetchImpl:fake(b.pages,limited),maxJobs:1})).length,1);assert.equal(limited.length,6)})

test('missing/hidden official handoff, wrong company and restricted or duplicate board queries fail',async()=>{for(const mutate of [b=>b.pages.get(C.officialUrl).body='<a>Careers</a>',b=>b.pages.get(C.officialUrl).body=`<!--<a href="${C.companyJobsUrl}">Careers</a>-->`,b=>b.pages.get(C.officialUrl).body=`<script>const x='<a href="${C.companyJobsUrl}">Careers</a>'</script>`,b=>b.pages.get(C.companyJobsUrl).body=b.pages.get(C.companyJobsUrl).body.replace('123456','999999'),b=>b.pages.get(C.companyJobsUrl).body=b.pages.get(C.companyJobsUrl).body.replace('&amp;trk=company','&amp;f_C=123456'),b=>b.pages.get(C.companyJobsUrl).body=b.pages.get(C.companyJobsUrl).body.replace('&amp;trk=company','&amp;location=India')]){const b=build();mutate(b);await assert.rejects(run(b),/handoff|identity|query/)}})

test('counts, raw anchors, raw cards and terminal proof must independently reconcile',async()=>{for(const mutate of [h=>h.replace('job-count">3','job-count">4'),h=>h.replace("You've viewed all jobs for this search",''),h=>h.replace('job-search-card"','unknown-row"'),h=>h.replace('base-search-card__title','unknown-title'),h=>h.replace('</ul>',`<li><a href="${roleUrl('1004')}">Unparsed role</a></li></ul>`),h=>h.replace('urn:li:jobPosting:1002','urn:li:jobPosting:1001')]){const b=build();b.pages.get(boardUrl).body=mutate(b.pages.get(boardUrl).body);await assert.rejects(run(b),/inventory|count|card|identity|terminal/)}})

test('every raw detail must retain title, employer, full JD, verified geography and future validity',async()=>{for(const mutate of [h=>h.replace('"name":"Verified Co"','"name":"Other Co"'),h=>h.replace('"addressCountry":"US"','"addressCountry":"IN"'),h=>h.replace('"addressCountry":"US"','"addressCountry":"ZZ"'),h=>h.replace('"addressCountry":"US"','"addressCountry":"QO"'),h=>h.replace('"validThrough":"2026-10-01"','"validThrough":"2026-08-01"'),h=>h.replace('<p>Required experience: 3+ years.</p>',''),h=>h.replace('role-at-verified-co-1002','role-at-verified-co-9000'),h=>h.replace('"addressLocality":"Indianapolis"','"addressLocality":"Chennai"')]){const b=build();b.pages.get(roleUrl('1002')).body=mutate(b.pages.get(roleUrl('1002')).body);await assert.rejects(run(b,{maxJobs:1}),/identity|description|geography|expired|country/)}})

test('schema-less exceptions require exact current ID/title/location and own role evidence',async()=>{for(const mutate of [h=>h.replaceAll('Location: Bangalore / Remote','Location: anywhere'),h=>h.replace('>India</span>','>Remote</span>'),h=>h.replace('<h1 class="top-card-layout__title">Remote Architect','<h1 class="top-card-layout__title">Different role')]){const b=build();b.pages.get(roleUrl('1003')).body=mutate(b.pages.get(roleUrl('1003')).body);await assert.rejects(run(b),/identity|geography|native|description/)}const b=build();b.rows[0].native=true;b.refresh();await assert.rejects(run(b),/schema|native/)} )

test('account application must be present and preserve exact role, without inventing offsite URL',async()=>{for(const mutate of [h=>h.replace('id="topbar-apply"','id="other"'),h=>h.replace('session_redirect=','wrong_redirect='),h=>h.replaceAll(encodeURIComponent(roleUrl('1001')),encodeURIComponent(roleUrl('9999'))),h=>h.replace('id="apply-modal"','id="other-modal"')]){const b=build();b.pages.get(roleUrl('1001')).body=mutate(b.pages.get(roleUrl('1001')).body);await assert.rejects(run(b),/application/)} })

test('caller abort after final detail body prevents partial result and retains original reason',async()=>{const b=build(),controller=new AbortController(),reason=new Error('caller stopped');const f=fake(b.pages);await assert.rejects(run(b,{signal:controller.signal,fetchImpl:async(u,o)=>{const r=await f(u,o);return{...r,text:async()=>{const h=await r.text();if(u===roleUrl('1003'))controller.abort(reason);return h}}}}),e=>e===reason);const already=new AbortController();already.abort(reason);await assert.rejects(run(b,{signal:already.signal,fetchImpl:()=>{throw Error('must not fetch')}}),e=>e===reason)})

test('request deadline remains finite for pending public transport',async()=>{const keep=setTimeout(()=>{},1000);try{await assert.rejects(runVerifiedEmployerLinkedIn({...C,requestTimeoutMs:10},{fetchImpl:async(u,{signal})=>new Promise((res,rej)=>signal.addEventListener('abort',()=>rej(signal.reason),{once:true}))}),e=>e.name==='TimeoutError')}finally{clearTimeout(keep)}})


test('mixed structured country locations remain intact while selecting India applicability',async()=>{const b=build();b.rows[0].location='Bengaluru, Karnataka, India / New York, United States';b.refresh();const p=b.pages.get(roleUrl('1001'));const m=p.body.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);const schema=JSON.parse(m[1]);schema.jobLocation=[schema.jobLocation,{'@type':'Place',address:{'@type':'PostalAddress',addressCountry:'US',addressLocality:'New York',addressRegion:null}}];p.body=p.body.replace(m[1],JSON.stringify(schema));const jobs=await run(b);assert.equal(jobs.length,2);assert.equal(jobs[0].country,'India');assert.equal(jobs[0].locations.length,2);assert(jobs[0].locations.some(x=>x.includes('United States')));assert(jobs[0].location.includes('New York'))})


test('board label case does not change exact numeric employer identity',async()=>{const b=build();b.pages.get(boardUrl).body=b.pages.get(boardUrl).body.replace('Verified Co Jobs in Worldwide','VERIFIED CO Jobs in Worldwide');assert.equal((await run(b)).length,2)})

test('explicit source-owned SPA handoff verifier receives only bounded same-origin requests and must prove success',async()=>{const b=build(),client='https://verified.example/main.js';b.pages.get(C.officialUrl).body='<title>Verified Co</title><script src="/main.js"></script>';b.pages.set(client,{url:client,body:'public careers renderer proof'});const options={fetchImpl:fake(b.pages),now:()=> '2026-09-13T00:00:00Z'};let seen=false;const callback=async({home,request,officialUrl})=>{assert(home.includes('src="/main.js"'));assert.equal(officialUrl,C.officialUrl);assert.equal(await request(client),'public careers renderer proof');seen=true;return true};assert.equal((await runVerifiedEmployerLinkedIn({...C,validateOfficialHandoff:callback},options)).length,2);assert(seen);await assert.rejects(runVerifiedEmployerLinkedIn({...C,validateOfficialHandoff:async()=>false},options),/handoff/);await assert.rejects(runVerifiedEmployerLinkedIn({...C,validateOfficialHandoff:async({request})=>{await request('https://other.example/script.js');return true}},options),/handoff|origin/);const controller=new AbortController(),reason=new Error('stop source verifier');await assert.rejects(runVerifiedEmployerLinkedIn({...C,validateOfficialHandoff:async()=>{controller.abort(reason);return true}},{...options,signal:controller.signal}),e=>e===reason)})
